/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"

#include "StdH.h"
ENGINE_API extern FLOAT ter_fLODMul;

#include <FogMarker.h>
#include <FogMarker_tables.h>
void CFogMarker::SetDefaultProperties(void) {
	m_fDepth = 10.0f;
	m_fAbove = 20.0f;
	m_fBelow = 20.0f;
	m_fFar = 100.0f;
	m_faType = FA_EXP ;
	m_fDensity = 0.1f;
	m_fgType = FG_CONSTANT ;
	m_fGraduation = 0.1f;
	m_bDensityDirect = TRUE ;
	m_fDensityPercentage = 0.95f;
	m_fDensityDistance = 10.0f;
	m_bGraduationDirect = TRUE ;
	m_fGraduationPercentage = 0.95f;
	m_fGraduationDistance = 10.0f;
	m_iSizeL = 32;
	m_iSizeH = 16;
	m_colColor = (C_WHITE  | CT_OPAQUE );
	CMarker::SetDefaultProperties();
}

#line 57 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
const CTString & CFogMarker::GetFogName(void) 
#line 58 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
{
#line 59 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
return m_strName ;
#line 60 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
}

#line 62 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
void CFogMarker::GetFog(class CFogParameters & fpFog) 
#line 63 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
{
#line 64 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
const FLOATmatrix3D & m  = GetRotationMatrix  ();
#line 65 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_vFogDir  (1) = m  (1 , 2);
#line 66 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_vFogDir  (2) = m  (2 , 2);
#line 67 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_vFogDir  (3) = m  (3 , 2);
#line 68 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
FLOAT fPos  = fpFog  . fp_vFogDir  % GetPlacement  () . pl_PositionVector ;
#line 69 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_colColor  = m_colColor ;
#line 70 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_atType  = (AttenuationType ) m_faType ;
#line 71 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_fDensity  = m_fDensity ;
#line 72 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_fgtType  = (FogGraduationType ) m_fgType ;
#line 73 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_fGraduation  = m_fGraduation ;
#line 74 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_fH0  = fPos  - m_fDepth  - m_fBelow ;
#line 75 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_fH1  = fPos  - m_fDepth ;
#line 76 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_fH2  = fPos ;
#line 77 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_fH3  = fPos  + m_fAbove ;
#line 78 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_fFar  = m_fFar  * ter_fLODMul ;
#line 79 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_iSizeH  = m_iSizeH ;
#line 80 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
fpFog  . fp_iSizeL  = m_iSizeL ;
#line 81 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
}
BOOL CFogMarker::
#line 83 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CFogMarker_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CFogMarker::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 85 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
InitAsEditorModel  ();
#line 86 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 87 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 90 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
SetModel  (MODEL_MARKER );
#line 91 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
SetModelMainTexture  (TEXTURE_MARKER );
#line 94 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
if(m_strName  == "Marker"){
#line 95 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_strName  = "Fog marker";
#line 96 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
}
#line 99 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
if(! m_bDensityDirect ){
#line 101 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
switch(m_faType ){
#line 102 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
case FA_LINEAR : 
#line 103 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fDensity  = m_fDensityPercentage  / m_fDensityDistance ;
#line 104 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
break ;
#line 105 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
case FA_EXP : 
#line 106 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fDensity  = - log  (1 - m_fDensityPercentage ) / m_fDensityDistance ;
#line 107 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
break ;
#line 108 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
case FA_EXP2 : 
#line 109 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fDensity  = Sqrt  (- log  (1 - m_fDensityPercentage )) / m_fDensityDistance ;
#line 110 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
break ;
#line 111 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
}
#line 112 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
}
#line 115 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
if(! m_bGraduationDirect ){
#line 117 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
switch(m_fgType ){
#line 118 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
case FG_LINEAR : 
#line 119 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fGraduation  = m_fGraduationPercentage  / m_fGraduationDistance ;
#line 120 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
break ;
#line 121 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
case FG_EXP : 
#line 122 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fGraduation  = - log  (1 - m_fGraduationPercentage ) / m_fGraduationDistance ;
#line 123 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
break ;
#line 124 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
}
#line 125 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
}
#line 129 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fDensity  = ClampDn  (m_fDensity  , 1E-6f);
#line 131 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fDepth  = ClampDn  (m_fDepth  , 0.001f);
#line 132 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fAbove  = ClampDn  (m_fAbove  , 0.001f);
#line 133 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fBelow  = ClampDn  (m_fBelow  , 0.001f);
#line 134 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_fFar  = ClampDn  (m_fFar  , 0.001f);
#line 136 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_iSizeL  = 1 << INDEX (Log2  (m_iSizeL ));
#line 137 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_iSizeH  = 1 << INDEX (Log2  (m_iSizeH ));
#line 138 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_iSizeL  = Clamp  (m_iSizeL  , INDEX (2) , INDEX (256));
#line 139 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
m_iSizeH  = Clamp  (m_iSizeH  , INDEX (2) , INDEX (256));
#line 141 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
Return(STATE_CURRENT,EVoid());
#line 141 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/FogMarker.es"
return TRUE; ASSERT(FALSE); return TRUE;};