/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"

#include "StdH.h"

#include <Light.h>
#include <Light_tables.h>
#line 33 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"


void CLight_OnInitClass(void)
{
	// init lens flares effects
	InitLensFlares();
}

void CLight_OnEndClass(void)
{
	// close lens flares effects
	CloseLensFlares();
}


void CLight::SetDefaultProperties(void) {
	m_colColor = C_GRAY ;
	m_colAmbient = C_BLACK ;
	m_fAmbientAttenuation = 0.0f;
	m_rFallOffRange = 8.0f;
	m_rHotSpotRange = 0.0f;
	m_itIllumination = 0;
	m_ltType = LT_POINT ;
	m_strDescription = "";
	m_strName = "Light";
	m_bDarkLight = FALSE ;
	m_fNearClip = 0.1f;
	m_fFarClip = 0.01f;
	m_bSubstractSectorAmbient = FALSE ;
	m_bRenderAsSmallLight = FALSE ;
	m_lftLensFlare = LFT_NONE ;
	m_bBackground = FALSE ;
	m_bLensFlareOnly = FALSE ;
	m_fnmLightAnimation = CTString("");
	m_iLightAnimation = 0;
	m_tmOffsetPhase = 0.0f;
	m_tmAniStartTime = 0.0f;
	m_fTimeMultiply = 1.0f;
	m_aoLightAnimation.SetData(NULL);

	m_bTargetable = FALSE ;
	m_bDynamic = FALSE ;
	m_bDiffusion = TRUE ;
	m_fnmAmbientLightAnimation = CTString("");
	m_iAmbientLightAnimation = 0;
	m_aoAmbientLightAnimation.SetData(NULL);

	CEntity::SetDefaultProperties();
}

#line 99 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
void CLight::Read_t(CTStream * istr,BOOL bNetwork) 
#line 100 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 101 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(bNetwork ){
#line 102 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = FALSE ;
#line 103 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 105 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = FALSE ;
#line 106 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_plsLight  = GetLightSource  ();
#line 107 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = FALSE ;
#line 109 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
CEntity  :: Read_t  (istr  , bNetwork );
#line 110 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}

#line 113 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
CAnimData * CLight::GetAnimData(SLONG slPropertyOffset) 
#line 114 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 115 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(slPropertyOffset  == offsetof  (CLight  , m_iLightAnimation ))
#line 116 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 117 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return m_aoLightAnimation  . GetData  ();
#line 118 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 119 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
else if(slPropertyOffset  == offsetof  (CLight  , m_iAmbientLightAnimation ))
#line 120 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 121 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return m_aoAmbientLightAnimation  . GetData  ();
#line 122 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 123 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
else 
#line 124 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 125 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return CEntity  :: GetAnimData  (slPropertyOffset );
#line 126 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 127 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}

#line 129 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
BOOL CLight::IsTargetable(void)const 
#line 130 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 131 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return m_bTargetable ;
#line 132 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}

#line 134 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
BOOL CLight::IsImportant(void)const 
#line 135 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 136 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return (m_ltType  == LT_DIRECTIONAL );
#line 137 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}

#line 140 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
BOOL CLight::HandleEvent(const CEntityEvent & ee) 
#line 141 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 143 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(ee  . ee_slEvent  == EVENTCODE_ERangeModelDestruction )
#line 144 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 145 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOn  (ENF_PROPSCHANGED );
#line 147 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_colColor  = C_BLACK ;
#line 148 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_colAmbient  = C_BLACK ;
#line 149 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 150 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 151 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 152 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return TRUE ;
#line 154 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 155 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
else if(ee  . ee_slEvent  == EVENTCODE_EChangeAnim )
#line 156 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 157 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOn  (ENF_PROPSCHANGED );
#line 158 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
EChangeAnim  & eChange  = (EChangeAnim  &) ee ;
#line 161 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_iLightAnimation  = eChange  . iLightAnim ;
#line 162 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoLightAnimation  . GetData  () != NULL )
#line 163 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 164 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_aoLightAnimation  . PlayAnim  (m_iLightAnimation  , eChange  . bLightLoop  ? AOF_LOOPING  : 0);
#line 165 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 168 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_iAmbientLightAnimation  = eChange  . iAmbientLightAnim ;
#line 169 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoAmbientLightAnimation  . GetData  () != NULL )
#line 170 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 171 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . PlayAnim  (m_iAmbientLightAnimation  , eChange  . bAmbientLightLoop  ? AOF_LOOPING  : 0);
#line 172 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 175 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if((m_aoLightAnimation  . GetData  () == NULL ) && (m_aoAmbientLightAnimation  . GetData  () == NULL ))
#line 176 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 177 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_colColor  = eChange  . colDiffuse ;
#line 178 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_colAmbient  = eChange  . colAmbient ;
#line 179 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 180 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 181 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 182 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 183 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return TRUE ;
#line 184 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 185 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return FALSE ;
#line 186 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}

#line 189 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
void CLight::MirrorAndStretch(FLOAT fStretch,BOOL bMirrorX) 
#line 190 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 192 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_rFallOffRange  *= fStretch ;
#line 193 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_rHotSpotRange  *= fStretch ;
#line 194 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_fNearClip  *= fStretch ;
#line 195 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_fFarClip  *= fStretch ;
#line 197 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}

#line 200 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
CLightSource * CLight::GetLightSource(void) 
#line 201 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 203 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(! m_bdfInitialized  . bdf_bValue ){
#line 205 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 206 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 207 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSourceWithNoDiscarding  (lsNew );
#line 208 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = TRUE ;
#line 209 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 210 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return & m_lsLightSource ;
#line 211 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}

#line 214 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
void CLight::SetupLightSource(CLightSource & lsNew) 
#line 215 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 216 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
switch(m_ltType ){
#line 217 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LT_POINT : 
#line 218 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LT_STRONG_POINT : 
#line 219 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  = LSF_CASTSHADOWS ;
#line 220 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 221 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LT_DIRECTIONAL : 
#line 222 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  = LSF_DIRECTIONAL  | LSF_CASTSHADOWS ;
#line 223 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 224 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LT_STRONG_AMBIENT : 
#line 225 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LT_AMBIENT : 
#line 226 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  = 0;
#line 227 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 228 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 229 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_bSubstractSectorAmbient ){lsNew  . ls_ulFlags  |= LSF_SUBSTRACTSECTORAMBIENT ;}
#line 230 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_bLensFlareOnly ){lsNew  . ls_ulFlags  |= LSF_LENSFLAREONLY ;}
#line 231 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDynamic ){lsNew  . ls_ulFlags  |= LSF_DYNAMIC ;}
#line 233 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDarkLight ){
#line 234 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  == LT_DIRECTIONAL ){
#line 235 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  &= ~ LSF_DARKLIGHT ;
#line 236 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_bDarkLight  = FALSE ;
#line 237 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 238 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  |= LSF_DARKLIGHT ;
#line 239 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 240 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 242 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDiffusion ){
#line 243 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDynamic  || m_ltType  == LT_AMBIENT  || m_ltType  == LT_STRONG_AMBIENT ){
#line 244 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  &= ~ LSF_DIFFUSION ;
#line 245 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_bDiffusion  = FALSE ;
#line 246 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 247 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  |= LSF_DIFFUSION ;
#line 248 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 249 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 251 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_rHotSpot  = m_rHotSpotRange ;
#line 252 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_rFallOff  = m_rFallOffRange ;
#line 253 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_fNearClipDistance  = m_fNearClip ;
#line 254 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_fFarClipDistance  = m_fFarClip ;
#line 256 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  == LT_STRONG_AMBIENT  || m_ltType  == LT_STRONG_POINT ){
#line 257 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_rHotSpot  = lsNew  . ls_rFallOff  * 0.9f;
#line 258 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 260 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_colColor  = m_colColor ;
#line 263 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_colAmbient  = m_colAmbient ;
#line 265 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(lsNew  . ls_ulFlags  & LSF_DIRECTIONAL ){
#line 266 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_colAmbient  = m_colAmbient ;
#line 267 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_fAmbientAttenuation  = m_fAmbientAttenuation ;
#line 268 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 269 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ubPolygonalMask  = (UBYTE ) m_itIllumination ;
#line 271 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
switch(m_lftLensFlare )
#line 272 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 273 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_NONE : 
#line 274 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = NULL ;
#line 275 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 276 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_STANDARD : 
#line 277 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftStandard ;
#line 278 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 279 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_STANDARD_REFLECTIONS : 
#line 280 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftStandardReflections ;
#line 281 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 282 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_YELLOW_STAR_RED_RING : 
#line 283 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftYellowStarRedRing ;
#line 284 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 285 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR_RED_RING : 
#line 286 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarRedRing ;
#line 287 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 288 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR : 
#line 289 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStar ;
#line 290 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 291 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_STAR_RED_RING_STREAKS : 
#line 292 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteStarRedRingStreaks ;
#line 293 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 294 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_STAR_RED_REFLECTIONS : 
#line 295 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteStarRedReflections ;
#line 296 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 297 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_BLUE_STAR_BLUE_REFLECTIONS : 
#line 298 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftBlueStarBlueReflections ;
#line 299 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 303 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR_RED_RING_FAR : 
#line 304 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftYellowStarRedRingFar ;
#line 305 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 306 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_FAR : 
#line 307 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowFar ;
#line 308 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 309 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR_NG : 
#line 310 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarNG ;
#line 311 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 312 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 316 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_paoLightAnimation  = NULL ;
#line 317 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 318 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_paoLightAnimation  = & m_aoLightAnimation ;
#line 319 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 322 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_paoAmbientLightAnimation  = NULL ;
#line 323 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoAmbientLightAnimation  . GetData  () != NULL ){
#line 324 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_paoAmbientLightAnimation  = & m_aoAmbientLightAnimation ;
#line 325 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 326 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}

#line 330 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SLONG CLight::GetUsedMemory(void) 
#line 331 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 333 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SLONG  slUsedMemory  = sizeof  (CLight ) - sizeof  (CEntity ) + CEntity  :: GetUsedMemory  ();
#line 335 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += m_strDescription  . Length  ();
#line 336 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += m_strName  . Length  ();
#line 337 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += m_fnmLightAnimation  . Length  ();
#line 338 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += m_fnmAmbientLightAnimation  . Length  ();
#line 339 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += 2 * sizeof  (CAnimObject);
#line 340 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return slUsedMemory ;
#line 341 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
BOOL CLight::
#line 345 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CLight_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CLight::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 347 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOn  (ENF_MARKDESTROY );
#line 348 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOn  (ENF_NONETCONNECT );
#line 349 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOff  (ENF_PROPSCHANGED );
#line 352 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_rFallOffRange  < 0){
#line 353 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_rFallOffRange  = 0.0f;
#line 354 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 355 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_rHotSpotRange  < 0){
#line 356 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_rHotSpotRange  = 0.0f;
#line 357 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 359 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_rHotSpotRange  > m_rFallOffRange ){
#line 360 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_rHotSpotRange  = m_rFallOffRange ;
#line 361 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 370 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_fNearClip  <= 0.01f){
#line 371 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_fNearClip  = 0.01f;
#line 372 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 374 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_fFarClip  <= 0){
#line 375 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_fFarClip  = 0.0f;
#line 376 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 379 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  != LT_DIRECTIONAL ){
#line 383 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_fAmbientAttenuation  = 0.0f;
#line 384 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 385 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_fAmbientAttenuation  = Clamp  (m_fAmbientAttenuation  , 0.0f , 1.0f);
#line 386 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 388 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
InitAsEditorModel  ();
#line 389 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 390 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 393 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_bRenderAsSmallLight )
#line 394 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 395 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
GetModelObject  () -> mo_Stretch  = FLOAT3D (0.25f , 0.25f , 0.25f);
#line 396 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 397 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
else 
#line 398 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 400 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  != LT_DIRECTIONAL ){
#line 401 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
const float  LIGHT_MINSIZE  = 0.5f;
#line 402 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
FLOAT fFactor  = Log2  (m_rFallOffRange ) * LIGHT_MINSIZE ;
#line 403 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(fFactor  < LIGHT_MINSIZE ){
#line 404 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
fFactor  = LIGHT_MINSIZE ;
#line 405 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 406 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
GetModelObject  () -> mo_Stretch  = FLOAT3D (fFactor  , fFactor  , fFactor );
#line 407 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 408 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 410 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
CTString strType ;
#line 411 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  == LT_POINT  || m_ltType  == LT_STRONG_POINT )
#line 412 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 413 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
strType  = "point";
#line 415 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetModel  (MODEL_LIGHT_SOURCE );
#line 417 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_POINT_LIGHT );
#line 418 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 420 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
else if(m_ltType  == LT_AMBIENT )
#line 421 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 422 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
strType  = "ambient";
#line 424 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetModel  (MODEL_LIGHT_SOURCE );
#line 426 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_AMBIENT_LIGHT );
#line 427 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 429 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
else if(m_ltType  == LT_STRONG_AMBIENT )
#line 430 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 431 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
strType  = "ambient";
#line 433 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetModel  (MODEL_LIGHT_SOURCE );
#line 435 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_REAL_AMBIENT_LIGHT );
#line 436 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 438 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
else if(m_ltType  == LT_DIRECTIONAL )
#line 439 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 440 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
strType  = "directional";
#line 442 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetModel  (MODEL_SPOT_LIGHT );
#line 444 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_SPOT_LIGHT );
#line 445 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 447 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDarkLight )
#line 448 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
{
#line 449 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
strType  = strType  + ", dark";
#line 450 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 453 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
try {
#line 454 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_aoLightAnimation  . SetData_t  (m_fnmLightAnimation );
#line 455 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}catch  (char  * strError ){
#line 456 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
WarningMessage  (TRANS  ("Cannot load '%s': %s") , (CTString &) m_fnmLightAnimation  , strError );
#line 457 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_fnmLightAnimation  = "";
#line 458 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 459 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 461 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_aoLightAnimation  . PlayAnim  (m_iLightAnimation  , AOF_LOOPING );
#line 462 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_aoLightAnimation  . ao_tmAnimStart  = - m_tmAniStartTime ;
#line 464 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 467 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
try {
#line 468 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . SetData_t  (m_fnmAmbientLightAnimation );
#line 469 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}catch  (char  * strError ){
#line 470 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
WarningMessage  (TRANS  ("Cannot load '%s': %s") , (CTString &) m_fnmAmbientLightAnimation  , strError );
#line 471 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_fnmAmbientLightAnimation  = "";
#line 472 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 473 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoAmbientLightAnimation  . GetData  () != NULL ){
#line 475 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . PlayAnim  (m_iAmbientLightAnimation  , AOF_LOOPING );
#line 476 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . ao_tmAnimStart  = - m_tmAniStartTime ;
#line 478 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 481 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 482 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 485 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(m_bBackground ){
#line 486 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetFlags  (GetFlags  () | ENF_BACKGROUND );
#line 487 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 488 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
SetFlags  (GetFlags  () & ~ ENF_BACKGROUND );
#line 489 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 492 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . ls_penEntity  = this ;
#line 493 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
if(! m_bdfInitialized  . bdf_bValue ){
#line 494 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSourceWithNoDiscarding  (lsNew );
#line 495 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = TRUE ;
#line 496 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 497 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 498 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
}
#line 501 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_plsLight  = & m_lsLightSource ;
#line 503 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
m_strDescription  . PrintF  ("%s:%g-%g" , 
#line 504 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
strType  , m_rHotSpotRange  , m_rFallOffRange );
#line 506 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
Return(STATE_CURRENT,EVoid());
#line 506 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Light.es"
return TRUE; ASSERT(FALSE); return TRUE;};