/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 3 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"

#include "StdH.h"

#include <Engine/Effect/CWorldTag.h>
#include <Engine/Effect/CEffectGroup.h>
#include <Engine/Effect/CEffectGroupManager.h>
#include <Engine/Effect/CSkaEffect.h>
#include <Engine/Graphics/Color.h>
#include <Engine/Entities/ItemData.h>
#include <Engine/Network/ItemTarget.h>
#include <Engine/Object/ActorMgr.h>
#include <deque>
#include <Engine/Entities/Skill.h>
#include <Engine/Network/MessageDefine.h>
#include "EntitiesMP/Common/CharacterDefinition.h"
#include <Engine/Info/MyInfo.h>

#define MOB_ATTACK_MOTION_NUM		(1)

//-----------------------------------------------------------------------------
// Purpose: 컨테이너 내의 모든 엔티티에 한번에 데미지를 줍니다.
// Input  : pEntity - 
//			sTI - 
//			vCenter - 
// Output : static void
//-----------------------------------------------------------------------------
void DamagedTargetsInRange(CEntity* pEntity, CSelectedEntities& dcEntities, enum DamageType dmtType, FLOAT fDamageAmmount, FLOAT3D vCenter, BOOL bSkill);

void ShotFallDown(FLOAT3D vStartPos, FLOAT3D vToTargetDir, FLOAT fMoveSpeed
				 , const char *szHitEffectName, const char *szFallObjEffectName
				 , bool bCritical);
void GetTargetDirection2(CEntity *penMe, CEntity *penTarget, FLOAT3D &vTargetPos, FLOAT3D &vDirection)
{
	if(penTarget == NULL) {return;}

	if(penTarget == penMe)
	{
		vTargetPos = penMe->en_plPlacement.pl_PositionVector;
		vDirection = FLOAT3D(0,1,1);
		return;
	}
	FLOAT3D vCurrentCenter(((EntityInfo*)(penMe->GetEntityInfo()))->vTargetCenter[0],
	((EntityInfo*)(penMe->GetEntityInfo()))->vTargetCenter[1],
	((EntityInfo*)(penMe->GetEntityInfo()))->vTargetCenter[2] );
	FLOAT3D vCurrentPos = penMe->en_plPlacement.pl_PositionVector + vCurrentCenter;
	FLOAT3D vTargetCenter(0, 0, 0);
	vTargetPos = FLOAT3D(0, 0, 0);
	vDirection = FLOAT3D(0, 0, 0);
	FLOAT size = 0;
	if(penTarget != NULL && penTarget->GetFlags()&ENF_ALIVE)
	{
		if(penTarget->en_RenderType == CEntity::RT_SKAMODEL)
		{
			// Bounding Box를 이용하여 Effect를 찍을 위치를 찾는다.
			FLOATaabbox3D bbox;
			penTarget->GetModelInstance()->GetCurrentColisionBox(bbox);
			FLOAT3D vRadius = (bbox.maxvect - bbox.minvect) * 0.5f * 0.4f/*단순히 원으로 하면 너무 큼. 사이즈 조절 상수*/;
			size = vRadius.Length();
		}
		vTargetCenter = FLOAT3D(((EntityInfo*)(penTarget->GetEntityInfo()))->vTargetCenter[0],
		((EntityInfo*)(penTarget->GetEntityInfo()))->vTargetCenter[1],
		((EntityInfo*)(penTarget->GetEntityInfo()))->vTargetCenter[2] );
		vTargetPos = penTarget->en_plPlacement.pl_PositionVector + vTargetCenter;
		vDirection = vTargetPos - vCurrentPos;
		vDirection.Normalize();
		vTargetPos -= vDirection * size;
	}
	vDirection.Normalize(); 				
};

ENGINE_API void SetDropItemModel(CEntity *penEntity, CItemData *pItemData, CItemTarget* pTarget);

#include <Pet.h>
#include <Pet_tables.h>
CEntityEvent *EPetAttackDamage::MakeCopy(void) { 	CEntityEvent *peeCopy = new EPetAttackDamage(*this); 	return peeCopy;}
SLONG EPetAttackDamage::GetSizeOf(void) { 	return sizeof(*this);}
EPetAttackDamage::EPetAttackDamage() : CEntityEvent(EVENTCODE_EPetAttackDamage) {
}
BOOL EPetAttackDamage::CheckIDs(void) {	return TRUE ; }

#line 85 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"

// info structure
static EntityInfo eiPetBoss = {
	EIBT_FLESH, 200.0f,
	//0.0f, 1.75f*m_fStretch, 0.0f,     // source (eyes)
	//0.0f, 1.30f*m_fStretch, 0.0f,     // target (body)
	0.0f, 1.75f*1.0f, 0.0f,     // source (eyes)
	0.0f, 1.30f*1.0f, 0.0f,     // target (body)
};

//안태훈 수정 시작	//(Effect Add & Modify for Close Beta)(0.1)
static INDEX g_iNPCMinBrightness = 32;	//명도 0~240
void CPet_OnInitClass(void)
{
	_pShell->DeclareSymbol("persistent user INDEX g_iNPCMinBrightness;", &g_iNPCMinBrightness);
}
//안태훈 수정 끝	//(Effect Add & Modify for Close Beta)(0.1)

void ShotMissile(CEntity *penShoter, const char *szShotPosTagName
				 , CEntity *penTarget, FLOAT fMoveSpeed
				 , const char *szHitEffectName, const char *szArrowEffectName
				 , bool bCritical
				 , FLOAT fHorizonalOffset = 0.0f, FLOAT fVerticalOffset = 0.0f	//-1.0f ~ 1.0f
				 , INDEX iArrowType = 0, const char *szMissileModel = NULL, CSelectedEntities* dcEntities = NULL);
void ShotMagicContinued(CEntity *penShoter, FLOAT3D vStartPos, FLOATquat3D qStartRot
				 , CEntity *penTarget, FLOAT fMoveSpeed
				 , const char *szHitEffectName, const char *szMagicEffectName
				 , bool bCritical, INDEX iOrbitType, BOOL bDirectTag = FALSE);

void CPet::SetDefaultProperties(void) {
	m_fBodyAnimTime = -1.0f;
	m_fStretch = 1.0f;
	iAnimPet_Walk = -1;
	iAnimPet_Idle1 = -1;
	iAnimPet_Idle2 = -1;
	iAnimPet_Run = -1;
	iAnimPet_Death = -1;
	iAnimPet_Wound = -1;
	iAnimPet_Attack = -1;
	iAnimPet_NormalBox = -1;
	iAnimPet_LevelUp = -1;
	iAnimPet_Skill01 = -1;
	iAnimPet_Skill02 = -1;
	iAnimPet_Skill03 = -1;
	iAnimPet_Skill04 = -1;
	iAnimPet_Skill05 = -1;
	iAnimPet_Skill01_01 = -1;
	iAnimPet_Skill01_02 = -1;
	iAnimPet_Pick = -1;
	iAnimPetType = -1;
	iAnimPetAge = -1;
	m_strName = "Enemy";
	m_EventType = EVENT_NONE ;
	m_penEventTarget = NULL;
	m_bIsRun = FALSE ;
	m_bDie = FALSE ;
	m_fActionAnimTime = 0.0f;
	m_bTransform = FALSE ;
	CPetBase::SetDefaultProperties();
}

#line 172 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
BOOL CPet::AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient) 
#line 173 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 176 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
g_iNPCMinBrightness  = Clamp  (g_iNPCMinBrightness  , (INDEX) 0 , (INDEX) 240);
#line 177 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
BOOL bRecalcAmbient  = FALSE ;
#line 178 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
UBYTE  ubAH  , ubAS  , ubAV ;
#line 179 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ColorToHSV  (colAmbient  , ubAH  , ubAS  , ubAV );
#line 180 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(ubAV  < g_iNPCMinBrightness )
#line 181 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 182 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
UBYTE  ubAR  , ubAG  , ubAB ;
#line 183 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ColorToRGB  (colAmbient  , ubAR  , ubAG  , ubAB );
#line 184 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ubAR  = g_iNPCMinBrightness ;
#line 185 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ubAG  = g_iNPCMinBrightness ;
#line 186 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ubAB  = g_iNPCMinBrightness ;
#line 187 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ColorToHSV  (RGBToColor  (ubAR  , ubAG  , ubAB ) , ubAH  , ubAS  , ubAV );
#line 188 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
bRecalcAmbient  = TRUE ;
#line 189 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 190 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(bRecalcAmbient ){colAmbient  = HSVToColor  (ubAH  , ubAS  , ubAV );}
#line 191 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE ;
#line 193 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
FLOAT CPet::GetLockRotationSpeed(void) 
#line 197 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 198 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return AngleDeg  (1800.0f);
#line 199 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
BOOL CPet::IsMovable() 
#line 203 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 206 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_bUseAI )
#line 207 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 208 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ObjInfo  * pInfo  = ObjInfo  :: getSingleton  ();
#line 209 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CPetTargetInfom  * pPetInfo  = pInfo  -> GetMyPetInfo  ();
#line 212 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if((pPetInfo  -> bIsActive  && (pPetInfo  -> fHungry  <= 0 || pPetInfo  -> fHealth  <= 0)) 
#line 213 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
|| m_bStuned  || m_bHold )
#line 214 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 215 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return FALSE ;
#line 216 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 217 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 218 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE ;
#line 219 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 221 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::OnInitialize(const CEntityEvent & eeInput) 
#line 222 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 223 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CPetBase  :: OnInitialize  (eeInput );
#line 224 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 226 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::OnEnd(void) 
#line 227 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 228 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CPetBase  :: OnEnd  ();
#line 229 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
CTString CPet::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 233 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 234 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CTString str ;
#line 235 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
str  . PrintF  (TRANS  ("A %s sent %s into the halls of Valhalla") , m_strName  , strPlayerName );
#line 236 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return str ;
#line 237 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 240 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void * CPet::GetEntityInfo(void) 
#line 241 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 242 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return & eiPetBoss ;
#line 243 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 245 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::Precache(void) 
#line 246 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 247 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CPetBase  :: Precache  ();
#line 250 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(en_pmiModelInstance ){en_pmiModelInstance  -> m_tmSkaTagManager  . SetOwner  (this );}
#line 252 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
BOOL CPet::IsPet(void)const 
#line 255 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 256 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE ;
#line 257 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 260 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::InflictDirectDamage(CEntity * penToDamage,CEntity * penInflictor,enum DamageType dmtType,
#line 261 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 262 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 263 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(penToDamage )
#line 264 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 265 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(! (penToDamage  -> GetFlags  () & ENF_ALIVE )){return ;}
#line 266 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX preHealth  , curHealth ;
#line 267 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
preHealth  = ((CUnit  *) penToDamage ) -> m_nPreHealth ;
#line 268 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
curHealth  = ((CUnit  *) penToDamage ) -> m_nCurrentHealth ;
#line 270 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(preHealth  != - 1)
#line 271 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 272 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
fDamageAmmount  = 1;
#line 273 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CUnit  *) penToDamage ) -> m_nCurrentHealth  = ((CUnit  *) penToDamage ) -> m_nPreHealth ;
#line 274 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 275 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else 
#line 276 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 277 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
fDamageAmmount  = 0;
#line 278 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 280 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(penToDamage  == INFO  () -> GetTargetEntity  (eTARGET ))
#line 281 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 282 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(penToDamage  -> IsCharacter  ())
#line 283 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 284 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> UpdateTargetInfo  (((CUnit  *) penToDamage ) -> m_nMaxiHealth  , ((CUnit  *) penToDamage ) -> m_nCurrentHealth  , ((CCharacter  *) penToDamage ) -> m_nPkMode  , ((CCharacter  *) penToDamage ) -> m_nPkState  , ((CCharacter  *) penToDamage ) -> m_nLegit );
#line 285 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 286 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else 
#line 287 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 288 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> UpdateTargetInfo  (((CUnit  *) penToDamage ) -> m_nMaxiHealth  , ((CUnit  *) penToDamage ) -> m_nCurrentHealth );
#line 289 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 290 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 293 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(penToDamage  -> IsEnemy  () && preHealth  >= 0)
#line 294 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 295 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
const INDEX iMobIndex  = ((CEnemy  *) penToDamage ) -> m_nMobDBIndex ;
#line 297 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(iMobIndex  == LORD_SYMBOL_INDEX )
#line 298 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 299 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CMobData  * MD  = CMobData  :: getData  (iMobIndex );
#line 300 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT fMaxHealth  = ((CUnit  *) penToDamage ) -> m_nMaxiHealth ;
#line 302 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if((curHealth  <= fMaxHealth  * 0.25f))
#line 303 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 304 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(((CUnit  *) penToDamage ) -> m_nPlayActionNum  != 0)
#line 305 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 306 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> SetSkaModel  ("data\\npc\\Gguard\\sword04.smc");
#line 307 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> GetModelInstance  () -> RefreshTagManager  ();
#line 308 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> GetModelInstance  () -> StretchModel  (FLOAT3D (MD  -> GetScale  () , MD  -> GetScale  () , MD  -> GetScale  ()));
#line 309 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CUnit  *) penToDamage ) -> m_nPlayActionNum  = 0;
#line 310 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 311 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 312 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if((curHealth  <= fMaxHealth  * 0.50f))
#line 313 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 314 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(((CUnit  *) penToDamage ) -> m_nPlayActionNum  != 1)
#line 315 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 316 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> SetSkaModel  ("data\\npc\\Gguard\\sword03.smc");
#line 317 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> GetModelInstance  () -> RefreshTagManager  ();
#line 318 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> GetModelInstance  () -> StretchModel  (FLOAT3D (MD  -> GetScale  () , MD  -> GetScale  () , MD  -> GetScale  ()));
#line 319 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CUnit  *) penToDamage ) -> m_nPlayActionNum  = 1;
#line 320 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 321 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 322 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if((curHealth  <= fMaxHealth  * 0.75f))
#line 323 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 324 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(((CUnit  *) penToDamage ) -> m_nPlayActionNum  != 2)
#line 325 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 326 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> SetSkaModel  ("data\\npc\\Gguard\\sword02.smc");
#line 327 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> GetModelInstance  () -> RefreshTagManager  ();
#line 328 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penToDamage  -> GetModelInstance  () -> StretchModel  (FLOAT3D (MD  -> GetScale  () , MD  -> GetScale  () , MD  -> GetScale  ()));
#line 329 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CUnit  *) penToDamage ) -> m_nPlayActionNum  = 2;
#line 330 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 331 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 332 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 333 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 335 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CUnit  *) penToDamage ) -> m_nPreHealth  = - 1;
#line 336 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 338 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CEntity  :: InflictDirectDamage  (penToDamage  , penInflictor  , dmtType  , 
#line 339 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
fDamageAmmount  , vHitPoint  , vDirection );
#line 341 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(penToDamage )
#line 342 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 343 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(((CUnit  *) penToDamage ) -> m_nCurrentHealth  <= 0 && penToDamage  != this )
#line 344 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 345 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CUnit  *) ((CEntity  *) penToDamage )) -> DeathNow  ();
#line 346 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 347 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 348 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 354 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 355 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 356 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 357 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(dmtType  != DMT_NONE  && fDamageAmmount  > 0)
#line 358 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 359 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vAxisY  (0 , 1 , 0);
#line 360 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT angle  = acos  (vDirection  % vAxisY );
#line 361 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D axis  = vAxisY  * vDirection ;
#line 362 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
axis  . Normalize  ();
#line 363 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOATquat3D quat ;
#line 364 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
quat  . FromAxisAngle  (axis  , angle );
#line 365 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
StartEffectGroup  ("Normal Hit" 
#line 366 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, _pTimer  -> GetLerpedCurrentTick  () , vHitPoint  , quat );
#line 367 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 369 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CPetBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 370 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 372 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
BOOL CPet::IsCommandAnimationPlaying() 
#line 373 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 375 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(IsAnimationPlaying  (iAnimPet_Skill01 ) || 
#line 376 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
IsAnimationPlaying  (iAnimPet_Skill02 ) || 
#line 377 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
IsAnimationPlaying  (iAnimPet_Skill03 ) || 
#line 378 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
IsAnimationPlaying  (iAnimPet_Skill04 ) || 
#line 379 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
IsAnimationPlaying  (iAnimPet_Skill05 ))
#line 380 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 381 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE ;
#line 382 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 383 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return FALSE ;
#line 384 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 386 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
BOOL CPet::TransformPetModel(INDEX iMobIndex,FLOAT fStretch) 
#line 387 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 388 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetPhysicsFlags  (GetPhysicsFlags  () & ~ (EPF_TRANSLATEDBYGRAVITY  | EPF_ORIENTEDBYGRAVITY ));
#line 389 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CMobData  * MD  = CMobData  :: getData  (iMobIndex );
#line 391 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetSkaModel  (MD  -> GetMobSmcFileName  ());
#line 393 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fprevStretch  = m_fStretch ;
#line 394 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fStretch  = fStretch ;
#line 396 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
StretchModel  (FLOAT3D (m_fStretch  , m_fStretch  , m_fStretch ));
#line 399 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_WALK_1  ] = iAnimPet_Walk ;
#line 400 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_IDLE_1  ] = iAnimPet_Idle1 ;
#line 401 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_IDLE_2  ] = iAnimPet_Idle2 ;
#line 402 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_RUN_1  ] = iAnimPet_Run ;
#line 403 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_PICK  ] = iAnimPet_Pick ;
#line 404 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_DAMAGE  ] = iAnimPet_Wound ;
#line 405 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_DIE  ] = iAnimPet_Death ;
#line 406 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_LEVELUP  ] = iAnimPet_LevelUp ;
#line 407 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_ATTACK  ] = iAnimPet_Attack ;
#line 409 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Walk  = ska_GetIDFromStringTable  (MD  -> GetAnimWalkName  ());
#line 410 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Idle1  = ska_GetIDFromStringTable  (MD  -> GetAnimDefaultName  ());
#line 411 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Idle2  = ska_GetIDFromStringTable  (MD  -> GetAnimDefault2Name  ());
#line 412 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Run  = ska_GetIDFromStringTable  (MD  -> GetAnimRunName  ());
#line 413 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Pick  = ska_GetIDFromStringTable  (MD  -> GetAnimAttackName  ());
#line 414 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Attack  = ska_GetIDFromStringTable  (MD  -> GetAnimAttackName  ());
#line 415 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Death  = ska_GetIDFromStringTable  (MD  -> GetAnimDeathName  ());
#line 416 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_LevelUp  = ska_GetIDFromStringTable  (MD  -> GetAnimWoundName  ());
#line 417 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Wound  = ska_GetIDFromStringTable  (MD  -> GetAnimWoundName  ());
#line 419 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
AddAnimation  (iAnimPet_Idle1  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1.0f , 0x03 , ESKA_MASTER_MODEL_INSTANCE );
#line 421 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetPhysicsFlags  (GetPhysicsFlags  () | EPF_TRANSLATEDBYGRAVITY  | EPF_ORIENTEDBYGRAVITY );
#line 422 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_bTransform  = TRUE ;
#line 424 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE ;
#line 425 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 427 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::ReturnPetModel(void) 
#line 428 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 429 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(! m_bTransform )
#line 430 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 431 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return ;
#line 432 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 434 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CTString strNewLook ;
#line 436 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fStretch  = m_fprevStretch ;
#line 438 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_bTransform  = FALSE ;
#line 439 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetPhysicsFlags  (GetPhysicsFlags  () & ~ (EPF_TRANSLATEDBYGRAVITY  | EPF_ORIENTEDBYGRAVITY ));
#line 440 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetSkaModel  (PetInfo  () . GetFileName  (m_iPetType  , m_iPetAge ));
#line 442 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Walk  = m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_WALK_1  ];
#line 443 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Idle1  = m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_IDLE_1  ];
#line 444 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Idle2  = m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_IDLE_2  ];
#line 445 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Run  = m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_RUN_1  ];
#line 446 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Pick  = m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_PICK  ];
#line 447 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Wound  = m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_DAMAGE  ];
#line 448 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Death  = m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_DIE  ];
#line 449 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_LevelUp  = m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_LEVELUP  ];
#line 450 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iAnimPet_Attack  = m_PetAnimationIndices  . m_iAnimation  [ PET_ANIM_ATTACK  ];
#line 452 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetPhysicsFlags  (GetPhysicsFlags  () | EPF_TRANSLATEDBYGRAVITY  | EPF_ORIENTEDBYGRAVITY );
#line 455 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_iPetColor  > 0)
#line 456 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 457 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CTString strTexFile  = PetInfo  () . GetColoredTexFileName  (m_iPetType  , m_iPetAge  , m_iPetColor );
#line 458 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> mi_aMeshInst  [ 0 ] . mi_tiTextures  [ 0 ] . ti_toTexture  . SetData_t  (strTexFile );
#line 459 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 460 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 466 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX CPet::AnimForDamage(FLOAT fDamage) 
#line 467 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 468 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_Wound  != - 1 && "Invalid Animation");
#line 469 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 472 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(! IsAnimationPlaying  (iAnimPet_Idle1 ) || ! IsAnimationPlaying  (iAnimPet_Idle2 ))
#line 473 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 474 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX animSet  , animIdx ;
#line 475 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
static INDEX animId  = ska_StringToID  ("mldam");
#line 476 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(this  -> en_pmiModelInstance  
#line 477 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
&& this  -> en_pmiModelInstance  -> FindAnimationByID  (animId  , & animSet  , & animIdx ))
#line 478 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 480 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
this  -> en_pmiModelInstance  -> AddAnimationChild  (animId  , AN_REMOVE_ON_END  , 1.0f , 0);
#line 481 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 482 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return animId ;
#line 483 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 485 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
NewClearState  (CLEAR_STATE_LENGTH );
#line 486 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Wound  , AN_CLEAR  , 1 , 0);
#line 488 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return iAnimPet_Wound ;
#line 489 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 492 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX CPet::AnimForDeath(void) 
#line 493 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 494 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_Death  != - 1 && "Invalid Animation");
#line 498 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 499 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
NewClearState  (CLEAR_STATE_LENGTH );
#line 500 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Death  , AN_NORESTART  , 1 , 0);
#line 502 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return iAnimPet_Death ;
#line 503 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 506 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT CPet::WaitForDust(FLOAT3D & vStretch) 
#line 507 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 509 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
vStretch  = FLOAT3D (1 , 1 , 1);
#line 510 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(GetModelInstance  () -> IsAnimationPlaying  (iAnimPet_Death ))
#line 511 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 512 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return 0.5f;
#line 513 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 514 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return - 1.0f;
#line 515 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 517 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::DeathNotify(void) 
#line 518 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 520 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
en_fDensity  = 500.0f;
#line 522 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_EventType  == EVENT_MOBDESTROY )
#line 523 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 524 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SendToTarget  (m_penEventTarget  , EET_TRIGGER  , this );
#line 525 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 526 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 529 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::ClickedEvent(void) 
#line 530 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 531 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_EventType  == EVENT_MOBCLICK )
#line 532 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 533 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SendToTarget  (m_penEventTarget  , EET_TRIGGER  , this );
#line 534 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 535 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 537 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::StandingAnim(void) 
#line 538 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 539 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_bIsRun  = FALSE ;
#line 540 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_Idle1  != - 1 && "Invalid Animation");
#line 541 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 542 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimation  (iAnimPet_Idle1  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 543 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Idle1  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 544 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 546 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::RunningAnim(void) 
#line 547 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 548 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_bIsRun  = TRUE ;
#line 549 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_Run  != - 1 && "Invalid Animation");
#line 550 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 551 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimation  (iAnimPet_Run  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 552 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Run  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 553 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 555 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::WalkingAnim(void) 
#line 556 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 557 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_bIsRun  = FALSE ;
#line 558 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_Walk  != - 1 && "Invalid Animation");
#line 559 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 560 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimation  (iAnimPet_Walk  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 561 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Walk  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 562 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 564 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::LevelUpAnim(void) 
#line 565 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 566 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_LevelUp  != - 1 && "Invalid Animation");
#line 567 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 568 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_LevelUp  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 569 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 571 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::SitAnim(void) 
#line 572 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 573 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_Skill01  != - 1 && "Invalid Animation");
#line 574 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 575 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Skill01  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 578 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 580 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::StandUpAnim(void) 
#line 581 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 582 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_Skill01_02  != - 1 && "Invalid Animation");
#line 583 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 584 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Skill01_02  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 587 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 589 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::SittingAnim(void) 
#line 590 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 591 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_Skill01_01  != - 1 && "Invalid Animation");
#line 592 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 593 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Skill01_01  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 598 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 600 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::PickAnim(void) 
#line 601 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 602 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimPet_Pick  != - 1 && "Invalid Animation");
#line 603 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 604 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Pick  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 605 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 607 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::SkillAnim(INDEX iAnimIndex,DWORD dwFlag,float fSpeed) 
#line 608 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 609 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (iAnimIndex  != - 1 && "Invalid Animation");
#line 610 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (GetModelInstance  () != NULL  && "Invalid ModelInstance");
#line 612 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimIndex  , dwFlag  , 1 , 0 , fSpeed );
#line 615 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 617 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::RotatingAnim(void) 
#line 618 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 619 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_bIsRun )
#line 620 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 621 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
RunningAnim  ();
#line 622 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 623 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else 
#line 624 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 625 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
WalkingAnim  ();
#line 626 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 627 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 630 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::EnemyPostInit(void) 
#line 631 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 633 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_soSound  . Set3DParameters  (30.0f , 5.0f , 1.0f , 1.0f);
#line 634 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 638 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::AddDeathItem(FLOAT3D pos,class CItemTarget * pItemTarget,class CItemData * pItemData) 
#line 639 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 640 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX cnt  = m_aDeathItemTargetDrop  . Count  ();
#line 641 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aDeathItemPosDrop  . Expand  (cnt  + 1);
#line 642 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aDeathItemPosDrop  [ cnt  ] = pos ;
#line 643 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aDeathItemTargetDrop  . Expand  (cnt  + 1);
#line 644 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aDeathItemTargetDrop  [ cnt  ] = pItemTarget ;
#line 645 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aDeathItemDataDrop  . Expand  (cnt  + 1);
#line 646 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aDeathItemDataDrop  [ cnt  ] = pItemData ;
#line 647 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
void CPet::DropDeathItem() 
#line 650 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 651 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
for(INDEX i  = 0;i  < m_aDeathItemTargetDrop  . Count  ();++ i )
#line 652 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 653 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CItemTarget  * pTarget  = NULL ;
#line 654 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
pTarget  = m_aDeathItemTargetDrop  [ i  ];
#line 656 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CItemData  * pItemData  = (CItemData  *) m_aDeathItemDataDrop  [ i  ];
#line 657 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
const char  * szItemData  = _pNetwork  -> GetItemName  (pItemData  -> GetItemIndex  ());
#line 658 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CEntity  * penEntity  = NULL ;
#line 659 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CPlacement3D plPlacement ;
#line 660 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
plPlacement  . pl_PositionVector  = m_aDeathItemPosDrop  [ i  ];
#line 661 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
plPlacement  . pl_OrientationAngle  = ANGLE3D (0.0f , 0.0f , 0.0f);
#line 662 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERT  (pTarget  -> m_pEntity  == NULL );
#line 663 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penEntity  = _pNetwork  -> ga_World  . CreateEntity_t  (plPlacement  , CLASS_ITEM  , - 1 , TRUE );
#line 665 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(penEntity  == NULL ){continue ;}
#line 667 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penEntity  -> SetNetworkID  (pTarget  -> GetSIndex  ());
#line 669 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
pTarget  -> m_pEntity  = penEntity ;
#line 670 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
pTarget  -> m_nIdxClient  = penEntity  -> en_ulID ;
#line 671 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
penEntity  -> en_strItemName  = szItemData ;
#line 672 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetDropItemModel  (penEntity  , pItemData  , pTarget );
#line 674 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ACTORMGR  () -> AddObject  (pTarget );
#line 677 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(pItemData  -> GetType  () == CItemData  :: ITEM_ETC  
#line 678 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
&& pItemData  -> GetType  () == CItemData  :: ITEM_ETC_MONEY )
#line 679 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 680 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CPlayerEntity  *) CEntity  :: GetPlayerEntity  (0)) -> PlayItemSound  (FALSE  , TRUE );
#line 681 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 682 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else 
#line 683 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 684 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CPlayerEntity  *) CEntity  :: GetPlayerEntity  (0)) -> PlayItemSound  (FALSE  , FALSE );
#line 685 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 686 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 688 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aDeathItemPosDrop  . Clear  ();
#line 689 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aDeathItemTargetDrop  . Clear  ();
#line 690 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aDeathItemDataDrop  . Clear  ();
#line 691 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}

#line 693 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
void CPet::SkillAndAttackFire(int num) 
#line 694 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 695 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(! (m_penEnemy  . ep_pen  != NULL  
#line 696 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
&& m_penEnemy  -> en_pmiModelInstance  != NULL  
#line 697 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
&& m_penEnemy  -> GetFlags  () & ENF_ALIVE ))
#line 698 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 699 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return ;
#line 700 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 701 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
switch(m_SkillEffectInfo  . iMissileType )
#line 702 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 703 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 0: 
#line 704 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 705 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vHitPoint ;
#line 706 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vHitDir ;
#line 707 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetTargetDirection2  (this  , m_penEnemy  , vHitPoint  , vHitDir );
#line 709 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_dcEnemies  . Count  () > 0)
#line 710 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 711 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
DamagedTargetsInRange  (this  , m_dcEnemies  , DMT_EXPLOSION  , 1 , vHitPoint  , TRUE );
#line 712 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_dcEnemies  . Clear  ();
#line 713 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 714 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else 
#line 715 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 717 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
this  -> InflictDirectDamage  (m_penEnemy  , this  , DMT_NONE  , 1 , vHitPoint  , vHitDir );
#line 718 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 720 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vAxisY  (0 , 1 , 0);
#line 721 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT angle  = acos  (vHitDir  % vAxisY );
#line 722 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D axis  = vAxisY  * vHitDir ;
#line 723 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
axis  . Normalize  ();
#line 724 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOATquat3D quat ;
#line 725 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
quat  . FromAxisAngle  (axis  , angle );
#line 726 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
StartEffectGroup  (m_SkillEffectInfo  . szEffectNameHit  
#line 727 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, _pTimer  -> GetLerpedCurrentTick  () 
#line 728 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, vHitPoint  , quat );
#line 729 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}break ;
#line 730 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 1: 
#line 731 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 732 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_dcEnemies  . Count  () > 0)
#line 733 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 734 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
for(ENTITIES_ITERATOR  it  = m_dcEnemies  . vectorSelectedEntities  . begin  ();
#line 735 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
it  != m_dcEnemies  . vectorSelectedEntities  . end  ();++ it )
#line 736 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 737 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CEntity  * pEn  = (* it );
#line 738 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(pEn  != NULL  && pEn  -> IsFlagOff  (ENF_DELETED ))
#line 739 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 740 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ShotMissile  (this  , "RHAND" , pEn  , m_SkillEffectInfo  . fMissileSpeed  , "Normal Hit" , "Normal Arrow Trace" , false );
#line 741 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 742 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 743 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 744 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else 
#line 745 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 746 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ShotMissile  (this  , "RHAND" , m_penEnemy  , m_SkillEffectInfo  . fMissileSpeed  , "Normal Hit" , "Normal Arrow Trace" , false );
#line 747 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 748 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}break ;
#line 749 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 2: 
#line 750 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 751 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
StartEffectGroup  (m_SkillEffectInfo  . szEffectNameHit  
#line 752 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, & m_penEnemy  -> en_pmiModelInstance  -> m_tmSkaTagManager  
#line 753 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, _pTimer  -> GetLerpedCurrentTick  ());
#line 754 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}break ;
#line 755 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 3: 
#line 756 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 757 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D lastEffectInfo  = m_penEnemy  -> en_plPlacement  . pl_PositionVector ;
#line 758 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
lastEffectInfo  (2) += 1;
#line 759 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_pSkillReadyEffect  != NULL  && CEffectGroupManager  :: Instance  () . IsValidCreated  (m_pSkillReadyEffect ))
#line 760 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 761 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
for(INDEX i  = 0;i  < m_pSkillReadyEffect  -> GetEffectCount  ();++ i )
#line 762 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 763 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CEffect  * pEffect  = m_pSkillReadyEffect  -> GetEffectKeyVector  () [ i  ] . m_pCreatedEffect ;
#line 764 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(pEffect  != NULL  && pEffect  -> GetType  () == ET_SKA )
#line 765 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 766 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CSkaEffect  * pSkaEffect  = (CSkaEffect  *) pEffect ;
#line 767 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
lastEffectInfo  = pSkaEffect  -> GetInstancePosition  ();
#line 768 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
break ;
#line 769 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 770 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 771 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(num  == m_SkillEffectInfo  . iFireDelayCount )
#line 772 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 773 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_pSkillReadyEffect  -> Stop  (0.04f);
#line 774 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 775 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 776 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_dcEnemies  . Count  () > 0)
#line 777 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 778 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
for(ENTITIES_ITERATOR  it  = m_dcEnemies  . vectorSelectedEntities  . begin  ();
#line 779 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
it  != m_dcEnemies  . vectorSelectedEntities  . end  ();++ it )
#line 780 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 781 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CEntity  * pEn  = (* it );
#line 782 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(pEn  != NULL  && pEn  -> IsFlagOff  (ENF_DELETED ))
#line 783 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 784 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ShotMagicContinued  (this  , lastEffectInfo  , FLOATquat3D (1 , 0 , 0 , 0) 
#line 785 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, pEn  , m_SkillEffectInfo  . fMissileSpeed  
#line 786 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, m_SkillEffectInfo  . szEffectNameHit  , m_SkillEffectInfo  . szEffectNameMissile  
#line 787 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, false  , 3);
#line 788 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 789 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 790 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 791 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else 
#line 792 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 793 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ShotMagicContinued  (this  , lastEffectInfo  , FLOATquat3D (1 , 0 , 0 , 0) 
#line 794 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, m_penEnemy  , m_SkillEffectInfo  . fMissileSpeed  
#line 795 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, m_SkillEffectInfo  . szEffectNameHit  , m_SkillEffectInfo  . szEffectNameMissile  
#line 796 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, false  , 3);
#line 797 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 798 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}break ;
#line 799 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 4: {}break ;
#line 800 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 5: {}break ;
#line 801 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 6: {}break ;
#line 802 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 7: {}break ;
#line 803 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 8: 
#line 804 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 805 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
StartEffectGroup  (m_SkillEffectInfo  . szEffectNameHit  
#line 806 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, & m_penEnemy  -> en_pmiModelInstance  -> m_tmSkaTagManager  
#line 807 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, _pTimer  -> GetLerpedCurrentTick  ());
#line 808 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_dcEnemies  . Count  () > 0)
#line 809 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 810 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
DamagedTargetsInRange  (this  , m_dcEnemies  , DMT_EXPLOSION  , 1 , FLOAT3D (0 , 0 , 0) , TRUE );
#line 811 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_dcEnemies  . Clear  ();
#line 812 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 813 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else 
#line 814 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 815 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
this  -> InflictDirectDamage  (m_penEnemy  , this  , DMT_NONE  , 1 , FLOAT3D (0 , 0 , 0) , FLOAT3D (0 , 0 , 0));
#line 816 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 817 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}break ;
#line 818 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 9: {}break ;
#line 820 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
case 21: 
#line 821 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 822 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CSkill  & skill  = _pNetwork  -> GetSkillData  (m_nCurrentSkillNum );
#line 823 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
static INDEX s_iFireBallCount  = 10;
#line 824 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
static FLOAT s_fFallHeight  = 3;
#line 825 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
static FLOAT s_fFallHeightVariation  = 3;
#line 826 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
static FLOAT s_fSpeed  = 5;
#line 827 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
static FLOAT s_fSpeedVariation  = 5;
#line 828 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
for(INDEX i  = 0;i  < s_iFireBallCount ;++ i )
#line 829 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 830 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D pos  = CRandomTable  :: Instance  () . GetRndCylinderPos  () * skill  . GetAppRange  ();
#line 831 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
pos  (2) = CRandomTable  :: Instance  () . GetRndFactor  () * s_fFallHeightVariation  + s_fFallHeight ;
#line 832 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
pos  += m_penEnemy  -> GetPlacement  () . pl_PositionVector ;
#line 833 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ShotFallDown  (pos  , FLOAT3D (0 , 1 , 0) , s_fSpeed  + s_fSpeedVariation  * CRandomTable  :: Instance  () . GetRndFactor  () 
#line 834 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, m_SkillEffectInfo  . szEffectNameHit  , m_SkillEffectInfo  . szEffectNameMissile  , FALSE );
#line 835 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 836 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}break ;
#line 838 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
default  :
#line 839 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 840 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ASSERTALWAYS  ("Something wrong... Plz check fire obj type of this skill.");
#line 841 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}break ;
#line 842 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 843 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
BOOL CPet::
#line 849 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPet_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPet::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 851 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(GetModelInstance  () == NULL )
#line 852 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 853 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
InitAsSkaEditorModel  ();
#line 854 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetSkaModel  ("Models\\Editor\\Ska\\Axis.smc");
#line 855 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EEnd  ());
#line 855 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE;
#line 856 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 858 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(GetModelInstance  () != NULL )
#line 859 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 860 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CSkaTag  tag ;
#line 861 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetName  ("__ROOT");
#line 862 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetOffsetRot  (GetEulerAngleFromQuaternion  (en_pmiModelInstance  -> mi_qvOffset  . qRot ));
#line 863 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> m_tmSkaTagManager  . Register  (& tag );
#line 864 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOATaabbox3D aabb ;
#line 865 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> GetAllFramesBBox  (aabb );
#line 866 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetName  ("CENTER");
#line 867 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetOffsetRot  (GetEulerAngleFromQuaternion  (en_pmiModelInstance  -> mi_qvOffset  . qRot ));
#line 868 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetOffsetPos  (0 , aabb  . Size  () (2) * 0.5f * GetModelInstance  () -> mi_vStretch  (2) , 0);
#line 869 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> m_tmSkaTagManager  . Register  (& tag );
#line 870 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetName  ("__TOP");
#line 871 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetOffsetRot  (GetEulerAngleFromQuaternion  (en_pmiModelInstance  -> mi_qvOffset  . qRot ));
#line 872 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetOffsetPos  (0 , aabb  . Size  () (2) * GetModelInstance  () -> mi_vStretch  (2) , 0);
#line 873 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> m_tmSkaTagManager  . Register  (& tag );
#line 874 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 877 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 879 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
en_sbNetworkType  = MSG_CHAR_PET ;
#line 882 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_iPetAge  != 2)
#line 883 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 884 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetPhysicsFlags  (EPF_ONBLOCK_CLIMBORSLIDE  
#line 885 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
| EPF_TRANSLATEDBYGRAVITY  
#line 887 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
| EPF_MOVABLE  
#line 888 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
| EPF_ABSOLUTETRANSLATE );
#line 890 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetCollisionFlags  (ECF_MODEL_NO_COLLISION );
#line 891 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 892 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else 
#line 893 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 896 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 897 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetPhysicsFlags  (EPF_MOVABLE );
#line 898 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetPhysicsFlags  (GetPhysicsFlags  () & ~ EPF_TRANSLATEDBYGRAVITY );
#line 899 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetPhysicsFlags  (EPF_MODEL_WALKING );
#line 900 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 903 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
en_tmMaxHoldBreath  = 60.0f;
#line 904 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
en_fDensity  = 1000.0f;
#line 906 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetFlagOn  (ENF_RENDERREFLECTION );
#line 909 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aWalkRotateSpeed  = AngleDeg  (1800.0f);
#line 910 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aAttackRotateSpeed  = AngleDeg  (1800.0f);
#line 911 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_aCloseRotateSpeed  = AngleDeg  (1800.0f);
#line 914 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fAttackFireTime  = 2.0f;
#line 915 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fCloseFireTime  = 2.0f;
#line 916 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fBlowUpAmount  = 80.0f;
#line 917 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fBodyParts  = 4;
#line 918 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fDamageWounded  = 0.0f;
#line 921 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> StretchModel  (FLOAT3D (m_fStretch  , m_fStretch  , m_fStretch ));
#line 922 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> mi_bRenderShadow  = TRUE ;
#line 924 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetHealth  (10000.0f);
#line 925 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ModelChangeNotify  ();
#line 929 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(GetModelInstance  ())
#line 930 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 931 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CSkaTag  tag ;
#line 932 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetName  ("__ROOT");
#line 933 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetOffsetRot  (GetEulerAngleFromQuaternion  (en_pmiModelInstance  -> mi_qvOffset  . qRot ));
#line 934 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> m_tmSkaTagManager  . Register  (& tag );
#line 935 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetName  ("__TOP");
#line 936 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetOffsetRot  (GetEulerAngleFromQuaternion  (en_pmiModelInstance  -> mi_qvOffset  . qRot ));
#line 937 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOATaabbox3D aabb ;
#line 938 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> GetAllFramesBBox  (aabb );
#line 939 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
tag  . SetOffsetPos  (0 , aabb  . Size  () (2) , 0);
#line 940 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> m_tmSkaTagManager  . Register  (& tag );
#line 941 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 944 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_bUseAI )
#line 945 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 946 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetTargetEntity  (CEntity  :: GetPlayerEntity  (0));
#line 947 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 950 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Jump(STATE_CURRENT, STATE_CPetBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CPet::
#line 956 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPet_Fire
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPet::Fire expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 958 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Jump(STATE_CURRENT, STATE_CPetBase_Fire, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CPet::
#line 961 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Hit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPet_Hit
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPet::Hit expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 963 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
STATE_CPet_NormalAttack, TRUE;
Jump(STATE_CURRENT, 0x4c7b0003, FALSE, EBegin());return TRUE;}BOOL CPet::H0x4c7b0003_Hit_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CPet_NormalAttack, TRUE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x4c7b0004, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CPet::H0x4c7b0004_Hit_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0004
const EEnd&__e= (EEnd&)__eeInput;
;
#line 964 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EReturn  ());
#line 964 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CPet::
#line 968 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
AttackTarget(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPet_AttackTarget
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPet::AttackTarget expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 970 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_vDesiredPosition  = PlayerDestinationPos  ();
#line 972 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX attackAnimID  = - 1;
#line 973 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
const int  iAttackMotion  = m_nAttackCnt  % MOB_ATTACK_MOTION_NUM ;
#line 974 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(iAttackMotion  == 0)
#line 975 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 976 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
attackAnimID  = iAnimPet_Attack ;
#line 977 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 978 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_SkillEffectInfo  . InitForNormalAttack  (CMobData  :: getData  (0) , attackAnimID );
#line 980 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(strlen  (m_SkillEffectInfo  . szEffectNameHit ) == 0){m_SkillEffectInfo  . szEffectNameHit  = "Normal Hit";}
#line 981 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_SkillEffectInfo  . iFireDelayCount  == 0)
#line 982 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 983 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_SkillEffectInfo  . iMissileType  = CSkill  :: MT_NONE ;
#line 984 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_SkillEffectInfo  . iFireDelayCount  = 1;
#line 985 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_SkillEffectInfo  . fFireDelay  [ 0 ] = GetAnimLength  (iAnimPet_Attack ) / 3;
#line 986 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 987 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
STATE_CPet_SkillAndMagicAnimation, TRUE;
Jump(STATE_CURRENT, 0x4c7b0006, FALSE, EBegin());return TRUE;}BOOL CPet::H0x4c7b0006_AttackTarget_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0006
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CPet_SkillAndMagicAnimation, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x4c7b0007, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CPet::H0x4c7b0007_AttackTarget_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0007
const EReturn&__e= (EReturn&)__eeInput;
;
#line 989 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EReturn  ());
#line 989 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CPet::
#line 992 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SkillingTarget(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPet_SkillingTarget
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPet::SkillingTarget expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 994 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_vDesiredPosition  = PlayerDestinationPos  ();
#line 1004 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CSkill  & skill  = _pNetwork  -> GetSkillData  (m_nCurrentSkillNum );
#line 1006 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_SkillEffectInfo  . InitForSkillAttack  (skill );
#line 1007 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
STATE_CPet_SkillAndMagicAnimation, TRUE;
Jump(STATE_CURRENT, 0x4c7b0009, FALSE, EBegin());return TRUE;}BOOL CPet::H0x4c7b0009_SkillingTarget_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0009
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CPet_SkillAndMagicAnimation, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x4c7b000a, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CPet::H0x4c7b000a_SkillingTarget_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b000a
const EReturn&__e= (EReturn&)__eeInput;
;
#line 1009 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EReturn  ());
#line 1009 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CPet::
#line 1013 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ActionAnimation(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPet_ActionAnimation
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPet::ActionAnimation expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 1015 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX iActionSkill  = - 1;
#line 1017 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_nPlayActionNum  == 271)
#line 1018 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1019 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iActionSkill  = iAnimPet_Skill01 ;
#line 1020 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1021 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if(m_nPlayActionNum  == 272)
#line 1022 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1023 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iActionSkill  = iAnimPet_Skill02 ;
#line 1024 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1025 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if(m_nPlayActionNum  == 273)
#line 1026 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1027 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iActionSkill  = iAnimPet_Skill03 ;
#line 1028 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1029 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if(m_nPlayActionNum  == 284)
#line 1030 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1031 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iActionSkill  = iAnimPet_Skill01 ;
#line 1032 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1033 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if(m_nPlayActionNum  == 285)
#line 1034 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1035 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iActionSkill  = iAnimPet_Skill03 ;
#line 1036 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1037 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if(m_nPlayActionNum  == 286)
#line 1038 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1039 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iActionSkill  = iAnimPet_Skill02 ;
#line 1040 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1041 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if(m_nPlayActionNum  == 287)
#line 1042 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1043 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iActionSkill  = iAnimPet_Skill05 ;
#line 1044 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1045 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if(m_nPlayActionNum  == 288)
#line 1046 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1047 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iActionSkill  = iAnimPet_Skill04 ;
#line 1048 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1049 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
else if(m_nPlayActionNum  == ACTION_NUM_PICKITEM )
#line 1050 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1051 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
iActionSkill  = iAnimPet_Pick ;
#line 1052 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1056 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimation  (iActionSkill  , AN_CLEAR  , 1.0f , 0);
#line 1057 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iActionSkill  , AN_CLEAR  , 1.0f , 0);
#line 1058 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fActionAnimTime  = GetModelInstance  () -> GetAnimLength  (iActionSkill );
#line 1060 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetTimerAfter(m_fActionAnimTime  - 0.1f);
Jump(STATE_CURRENT, 0x4c7b000c, FALSE, EBegin());return TRUE;}BOOL CPet::H0x4c7b000c_ActionAnimation_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b000c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x4c7b000d, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CPet::H0x4c7b000d_ActionAnimation_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b000d
;
#line 1070 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
StandingAnim  ();
#line 1072 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EReturn  ());
#line 1072 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CPet::
#line 1075 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
AttackAnimation(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPet_AttackAnimation
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPet::AttackAnimation expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 1077 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
const int  iAttackMotion  = m_nAttackCnt  % MOB_ATTACK_MOTION_NUM ;
#line 1078 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(iAttackMotion  == 0)
#line 1079 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1080 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Attack  , AN_CLEAR  , 1.0f , 0);
#line 1081 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1083 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fAttackFrequency  = 0.25f;
#line 1084 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fAttackStartTime  = _pTimer  -> CurrentTick  ();
#line 1085 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fImpactTime  = GetAnimLength  (iAnimPet_Attack ) / 3;
#line 1087 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Jump(STATE_CURRENT,0x4c7b0011, FALSE, EInternal());return TRUE;}BOOL CPet::H0x4c7b0011_AttackAnimation_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0011
if(!(_pTimer  -> CurrentTick  () - m_fAttackStartTime  < GetAnimLength  (iAnimPet_Attack ) * 0.8f)){ Jump(STATE_CURRENT,0x4c7b0012, FALSE, EInternal());return TRUE;}
#line 1089 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetTimerAfter(m_fAttackFrequency );
Jump(STATE_CURRENT, 0x4c7b000f, FALSE, EBegin());return TRUE;}BOOL CPet::H0x4c7b000f_AttackAnimation_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b000f
switch(__eeInput.ee_slEvent)
#line 1090 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{case(EVENTCODE_EBegin):
#line 1092 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{const EBegin&e= (EBegin&)__eeInput;

#line 1093 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_bMoving )
#line 1094 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1098 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EReturn  ());
#line 1098 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE;
#line 1099 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1101 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fMoveSpeed  = 0.0f;
#line 1102 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
ULONG  ulFlags  = SetDesiredMovement  ();
#line 1104 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(_pTimer  -> CurrentTick  () - m_fAttackStartTime  > m_fImpactTime )
#line 1105 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1106 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SendEvent  (EPetAttackDamage  ());
#line 1107 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fImpactTime  = 1000.0f;
#line 1108 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1110 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE;
#line 1111 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}ASSERT(FALSE);break;case(EVENTCODE_EPetBaseDamage):
#line 1113 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{const EPetBaseDamage&eEBDamage= (EPetBaseDamage&)__eeInput;

#line 1115 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fDamageConfused  -= eEBDamage  . fAmount ;
#line 1116 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_fDamageConfused  < 0.001f)
#line 1117 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1118 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fDamageConfused  = m_fDamageWounded ;
#line 1120 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX animSet  , animIdx ;
#line 1121 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
static INDEX animId  = ska_StringToID  ("mldam");
#line 1122 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(this  -> en_pmiModelInstance  
#line 1123 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
&& this  -> en_pmiModelInstance  -> FindAnimationByID  (animId  , & animSet  , & animIdx ))
#line 1124 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1126 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
this  -> en_pmiModelInstance  -> AddAnimationChild  (animId  , AN_REMOVE_ON_END  , 1.0f , 0);
#line 1127 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1128 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1129 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE;
#line 1130 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}ASSERT(FALSE);break;case(EVENTCODE_EPetAttackDamage):
#line 1132 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{const EPetAttackDamage&eAttackDamage= (EPetAttackDamage&)__eeInput;

#line 1135 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
CEntity  * pen  = m_penEnemy ;
#line 1136 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vCurrentCenter  (((EntityInfo  *) (this  -> GetEntityInfo  ())) -> vTargetCenter  [ 0 ] , 
#line 1137 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((EntityInfo  *) (this  -> GetEntityInfo  ())) -> vTargetCenter  [ 1 ] , 
#line 1138 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((EntityInfo  *) (this  -> GetEntityInfo  ())) -> vTargetCenter  [ 2 ]);
#line 1139 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vCurrentPos  = this  -> en_plPlacement  . pl_PositionVector  + vCurrentCenter ;
#line 1140 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vTargetCenter  (0 , 0 , 0);
#line 1141 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vTargetPos  (0 , 0 , 0);
#line 1142 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vDirection  (0 , 0 , 0);
#line 1143 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT size  = 0;
#line 1144 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(pen  != NULL  && pen  -> GetFlags  () & ENF_ALIVE )
#line 1145 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1146 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(pen  -> en_RenderType  == RT_SKAMODEL )
#line 1147 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1149 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOATaabbox3D bbox ;
#line 1150 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
pen  -> GetModelInstance  () -> GetCurrentColisionBox  (bbox );
#line 1151 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT3D vRadius  = (bbox  . maxvect  - bbox  . minvect ) * 0.5f * 0.4f;
#line 1152 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
size  = vRadius  . Length  ();
#line 1153 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1154 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
vTargetCenter  = FLOAT3D (((EntityInfo  *) (pen  -> GetEntityInfo  ())) -> vTargetCenter  [ 0 ] , 
#line 1155 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((EntityInfo  *) (pen  -> GetEntityInfo  ())) -> vTargetCenter  [ 1 ] , 
#line 1156 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((EntityInfo  *) (pen  -> GetEntityInfo  ())) -> vTargetCenter  [ 2 ]);
#line 1157 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
vTargetPos  = pen  -> en_plPlacement  . pl_PositionVector  + vTargetCenter ;
#line 1158 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
vDirection  = vTargetPos  - vCurrentPos ;
#line 1159 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
vDirection  . Normalize  ();
#line 1160 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
vTargetPos  -= vDirection  * size ;
#line 1161 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1162 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
vDirection  . Normalize  ();
#line 1167 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
this  -> InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , (int ) 1 , vTargetPos  , vDirection );
#line 1169 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CLiveEntity  *) ((CEntity  *) m_penEnemy )) -> SetHealth  (1000.0f);
#line 1171 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fImpactTime  = 1000.0f;
#line 1173 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
UnsetTimer();Jump(STATE_CURRENT,0x4c7b0010, FALSE, EInternal());return TRUE;
#line 1174 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x4c7b0010, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 1176 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}return TRUE;}BOOL CPet::H0x4c7b0010_AttackAnimation_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0010
Jump(STATE_CURRENT,0x4c7b0011, FALSE, EInternal());return TRUE;
#line 1177 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}BOOL CPet::H0x4c7b0012_AttackAnimation_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0012

#line 1179 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_penKillEnemy  != NULL )
#line 1180 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1181 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(((CUnit  *) ((CEntity  *) m_penKillEnemy )) -> m_nCurrentHealth  <= 0)
#line 1182 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1183 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
((CUnit  *) ((CEntity  *) m_penKillEnemy )) -> DeathNow  ();
#line 1184 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1185 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_penKillEnemy  = NULL ;
#line 1186 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1189 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_bAttack  = FALSE ;
#line 1190 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_bMoving  = FALSE ;
#line 1191 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_bStop  = FALSE ;
#line 1192 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
StandingAnim  ();
#line 1193 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetNoTargetEntity  ();
#line 1195 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EReturn  ());
#line 1195 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CPet::
#line 1198 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SkillAndMagicAnimation(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPet_SkillAndMagicAnimation
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPet::SkillAndMagicAnimation expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 1200 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_SkillEffectInfo  . dwValidValue  != 0)
#line 1201 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1202 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_SkillEffectInfo  . dwValidValue  = 0xBAD0BEEF;
#line 1203 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EReturn  ());
#line 1203 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE;
#line 1204 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1206 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fAttackFrequency  = 0.05f;
#line 1207 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fAttackStartTime  = _pTimer  -> GetLerpedCurrentTick  ();
#line 1208 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fImpactTime  = GetAnimLength  (iAnimPet_Attack ) / 3;
#line 1210 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (m_SkillEffectInfo  . iAnimatioID  , AN_CLEAR  , 1.0f , 0);
#line 1212 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_nEffectStep  = 1;
#line 1213 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_pSkillReadyEffect  = NULL ;
#line 1214 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_pSkillReadyEffect  = StartEffectGroup  (m_SkillEffectInfo  . szEffectNameCast  
#line 1215 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, & en_pmiModelInstance  -> m_tmSkaTagManager  
#line 1216 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
, _pTimer  -> GetLerpedCurrentTick  ());
#line 1218 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Jump(STATE_CURRENT,0x4c7b0016, FALSE, EInternal());return TRUE;}BOOL CPet::H0x4c7b0016_SkillAndMagicAnimation_03(const CEntityEvent &__eeInput)
#line 1219 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0016
if(!(_pTimer  -> GetLerpedCurrentTick  () - m_fAttackStartTime  < GetAnimLength  (m_SkillEffectInfo  . iAnimatioID ) * 0.8f)){ Jump(STATE_CURRENT,0x4c7b0017, FALSE, EInternal());return TRUE;}
#line 1220 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetTimerAfter(m_fAttackFrequency );
Jump(STATE_CURRENT, 0x4c7b0014, FALSE, EBegin());return TRUE;}BOOL CPet::H0x4c7b0014_SkillAndMagicAnimation_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0014
switch(__eeInput.ee_slEvent)
#line 1221 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{case(EVENTCODE_EBegin):
#line 1223 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{const EBegin&e= (EBegin&)__eeInput;

#line 1224 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_bMoving  || m_bStop )
#line 1225 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1226 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
DestroyEffectGroupIfValid  (m_pSkillReadyEffect );
#line 1227 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
GetModelInstance  () -> AddAnimationChild  (iAnimPet_Idle1  , AN_LOOPING  | AN_NORESTART  | AN_CLEAR  , 1 , 0);
#line 1228 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_SkillEffectInfo  . dwValidValue  = 0xBAD0BEEF;
#line 1229 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EReturn  ());
#line 1229 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE;
#line 1230 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1232 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fMoveSpeed  = 0.0f;
#line 1233 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_penEnemy  . ep_pen  != this )
#line 1234 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1235 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetDesiredMovement  ();
#line 1236 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1238 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
FLOAT time  = _pTimer  -> GetLerpedCurrentTick  () - m_fAttackStartTime ;
#line 1239 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(time  >= m_SkillEffectInfo  . fFireDelay  [ 0 ] && m_nEffectStep  == 1 && m_SkillEffectInfo  . iFireDelayCount  > 0)
#line 1240 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1241 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
++ m_nEffectStep ;
#line 1242 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SkillAndAttackFire  (1);
#line 1243 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1244 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(time  >= m_SkillEffectInfo  . fFireDelay  [ 1 ] && m_nEffectStep  == 2 && m_SkillEffectInfo  . iFireDelayCount  > 1)
#line 1245 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1246 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
++ m_nEffectStep ;
#line 1247 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SkillAndAttackFire  (2);
#line 1248 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1249 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(time  >= m_SkillEffectInfo  . fFireDelay  [ 2 ] && m_nEffectStep  == 3 && m_SkillEffectInfo  . iFireDelayCount  > 2)
#line 1250 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1251 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
++ m_nEffectStep ;
#line 1252 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SkillAndAttackFire  (3);
#line 1253 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1254 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(time  >= m_SkillEffectInfo  . fFireDelay  [ 3 ] && m_nEffectStep  == 4 && m_SkillEffectInfo  . iFireDelayCount  > 3)
#line 1255 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1256 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
++ m_nEffectStep ;
#line 1257 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SkillAndAttackFire  (4);
#line 1258 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1259 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE;
#line 1260 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}ASSERT(FALSE);break;case(EVENTCODE_EEnemyBaseDamage):
#line 1262 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{const EEnemyBaseDamage&eEBDamage= (EEnemyBaseDamage&)__eeInput;

#line 1264 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fDamageConfused  -= eEBDamage  . fAmount ;
#line 1265 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(m_fDamageConfused  < 0.001f)
#line 1266 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1267 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_fDamageConfused  = m_fDamageWounded ;
#line 1269 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX animSet  , animIdx ;
#line 1270 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
static INDEX animId  = ska_StringToID  ("mldam");
#line 1271 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(this  -> en_pmiModelInstance  
#line 1272 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
&& this  -> en_pmiModelInstance  -> FindAnimationByID  (animId  , & animSet  , & animIdx ))
#line 1273 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1275 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
this  -> en_pmiModelInstance  -> AddAnimationChild  (animId  , AN_REMOVE_ON_END  , 1.0f , 0);
#line 1276 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1277 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1278 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE;
#line 1279 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x4c7b0015, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 1281 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}return TRUE;}BOOL CPet::H0x4c7b0015_SkillAndMagicAnimation_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0015
Jump(STATE_CURRENT,0x4c7b0016, FALSE, EInternal());return TRUE;
#line 1282 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}BOOL CPet::H0x4c7b0017_SkillAndMagicAnimation_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0017

#line 1284 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_nEffectStep  = 0;
#line 1285 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_SkillEffectInfo  . dwValidValue  = 0xBAD0BEEF;
#line 1286 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EReturn  ());
#line 1286 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CPet::
#line 1290 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
NormalAttack(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPet_NormalAttack
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPet::NormalAttack expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 1293 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
StandingAnim  ();
#line 1294 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
SetTimerAfter(0.8f + FRnd  () * 0.25f);
Jump(STATE_CURRENT, 0x4c7b0019, FALSE, EBegin());return TRUE;}BOOL CPet::H0x4c7b0019_NormalAttack_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b0019
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x4c7b001a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CPet::H0x4c7b001a_NormalAttack_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b001a
;
#line 1296 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
INDEX attackAnimID  = - 1;
#line 1297 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
const int  iAttackMotion  = rand  () % MOB_ATTACK_MOTION_NUM ;
#line 1298 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
if(iAttackMotion  == 0)
#line 1299 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
{
#line 1300 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
attackAnimID  = iAnimPet_Attack ;
#line 1301 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
}
#line 1303 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
m_nAttackCnt  = attackAnimID ;
#line 1305 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
STATE_CPet_AttackTarget, TRUE;
Jump(STATE_CURRENT, 0x4c7b001b, FALSE, EBegin());return TRUE;}BOOL CPet::H0x4c7b001b_NormalAttack_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b001b
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CPet_AttackTarget, TRUE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x4c7b001c, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CPet::H0x4c7b001c_NormalAttack_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x4c7b001c
const EEnd&__e= (EEnd&)__eeInput;
;
#line 1309 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
Return(STATE_CURRENT,EEnd  ());
#line 1309 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Pet.es"
return TRUE; ASSERT(FALSE); return TRUE;};