/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"

#include "StdH.h"
#include "EntitiesMP/Player.h"
#include "EntitiesMP/PlayerWeapons.h"
#include <Engine/Interface/UIManager.h>
#include <Engine/Interface/UIInitJob.h>

#include <PlayerView.h>
#include <PlayerView_tables.h>
CEntityEvent *EViewInit::MakeCopy(void) { 	CEntityEvent *peeCopy = new EViewInit(*this); 	return peeCopy;}
SLONG EViewInit::GetSizeOf(void) { 	return sizeof(*this);}
EViewInit::EViewInit() : CEntityEvent(EVENTCODE_EViewInit) {
	ClearToDefault(eidOwner);
	ClearToDefault(eidCamera);
	ClearToDefault(vtView);
	ClearToDefault(bDeathFixed);
}
BOOL EViewInit::CheckIDs(void) {	return TRUE && eidOwner.IsValid()&& eidCamera.IsValid(); }

#line 26 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"

extern ENGINE_API INDEX g_iCountry;
#include <Engine/GlobalDefinition.h>
#include <Engine/Effect/CCameraEffect.h>
extern ENGINE_API CCameraEffect::CCameraValue g_cvCameraShake;
FLOAT3D g_vOldCameraShake;
FLOAT3D g_vOldCameraPosByCharCoord;

void CPlayerView_Precache(void) 
{
	CDLLEntityClass *pdec = &CPlayerView_DLLClass;
	pdec->PrecacheModel(MODEL_MARKER);
	pdec->PrecacheTexture(TEXTURE_MARKER);
}

extern ENGINE_API CViewPort	*_pvpViewPortMain;

static FLOAT m_fLastTime;
static BOOL m_bLockRotate = FALSE;

// FIXME : 임시적으로 만든 변수.
// 추적 모드를 쓸 것인지 기존 방식을 쓸것인지...
static BOOL m_bUseTraceMode	= FALSE;

static ANGLE3D _aAbs;
static CPlacement3D _plNew;
static CPlacement3D _plOld;

void CameraEffect(const CPlacement3D &plPlr, CPlacement3D &plCam)
{
	CPlacement3D plNew = plCam;
	//twist 처리
	if(g_cvCameraShake.m_fTwist != 0)
	{
		plNew.pl_OrientationAngle(3) += g_cvCameraShake.m_fTwist;
	}

	//카메라 좌표기준 이동처리
	FLOATmatrix3D m;
	if(g_cvCameraShake.m_fHorizonal != 0
	|| g_cvCameraShake.m_fVertical != 0
	|| g_cvCameraShake.m_fZoom != 0)
	{
		MakeRotationMatrixFast(m, plCam.pl_OrientationAngle);
		FLOAT3D vMoveByCamCoord(g_cvCameraShake.m_fHorizonal
								, g_cvCameraShake.m_fVertical
								, g_cvCameraShake.m_fZoom);
		RotateVector(vMoveByCamCoord, m);
		plNew.pl_PositionVector += vMoveByCamCoord;
	}

	//캐릭터 좌표기준 이동처리
	if(g_cvCameraShake.m_vMoveByCharCoord(1) != 0
	|| g_cvCameraShake.m_vMoveByCharCoord(2) != 0
	|| g_cvCameraShake.m_vMoveByCharCoord(3) != 0)
	{
		MakeRotationMatrixFast(m, plPlr.pl_OrientationAngle);
		FLOAT3D vMoveByChaCoord = g_cvCameraShake.m_vMoveByCharCoord;
		RotateVector(vMoveByChaCoord, m);
		plNew.pl_PositionVector += vMoveByChaCoord;
	}

	plCam = plNew;
}

void CPlayerView::SetDefaultProperties(void) {
	m_penOwner = NULL;
	m_iViewType = 0;
	m_fDistance = 1.0f;
	m_vZLast = FLOAT3D(0 , 0 , 0);
	m_vTargetLast = FLOAT3D(0 , 0 , 0);
	m_bFixed = FALSE ;
	m_fCameraHeight = 0.0f;
	m_bInit = FALSE ;
	m_aCurAngle = 0.0f;
	m_aAccel = 0.0f;
	m_aVelocity = 0.0f;
	m_PrevModelColor = 0.0f;
	m_bPrevModelColor = FALSE ;
	m_fFaceChangeDistance = 0.0f;
	m_penPrediction = NULL;
	CMovableEntity::SetDefaultProperties();
}

#line 124 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
void CPlayerView::PreMoving() {}

#line 125 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
void CPlayerView::DoMoving() 
#line 126 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 127 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
en_plLastPlacement  = GetPlacement  ();
#line 128 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}

#line 129 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
void CPlayerView::PostMoving() 
#line 130 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 132 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(m_bUseTraceMode )
#line 133 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 135 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetCameraPosition  ();
#line 136 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 138 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 139 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 140 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> inp_bFreeMode )
#line 141 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 142 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetCameraFreeMode  ();
#line 143 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 144 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else if(SE_Get_UIManagerPtr  () -> GetInitJob  () -> IsFaceDecoMode  ())
#line 145 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 146 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetCameraDecoMode  ();
#line 147 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 148 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 149 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 150 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetCameraPositionEx  ();
#line 151 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 152 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 153 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}

#line 154 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CPlacement3D CPlayerView::GetLerpedPlacement(void)const 
#line 155 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 156 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fLerpFactor ;
#line 157 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fLerpFactor  = _pTimer  -> GetLerpFactor2  ();
#line 158 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
return LerpPlacementsPrecise  (en_plLastPlacement  , en_plPlacement  , fLerpFactor );
#line 161 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}

#line 164 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
void CPlayerView::RenderParticles(void) 
#line 165 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 166 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(Particle_GetViewer  () == this ){
#line 167 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
Particles_ViewerLocal  (m_penOwner );
#line 168 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 169 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}

#line 172 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
void CPlayerView::UnlockRotate() 
#line 173 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 174 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_bLockRotate  = FALSE ;
#line 175 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}

#line 180 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
void CPlayerView::SetCameraPositionEx() 
#line 181 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 183 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fDistance  = 1.0f;
#line 185 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fDistanceLimit  = 9.5f;
#line 186 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
static FLOAT fDistanceTmp  = 0.0f;
#line 187 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
BOOL bHit  = FALSE ;
#line 194 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pNetwork  -> MyCharacterInfo  . m_ModelColor  > 0)
#line 195 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 196 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceLimit  = 24.5f;
#line 197 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 219 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
static BOOL bLimitIn  = FALSE ;
#line 220 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
static FLOAT fSmooth  = 0.0f;
#line 222 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT zoomMin  = - 2.0f;
#line 225 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(((CPlayer  &) * m_penOwner ) . m_bRide )
#line 226 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 227 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(((CPlayer  &) * m_penOwner ) . m_iRideType  % 2 == 0)
#line 228 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 229 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
zoomMin  = 3.0f;
#line 230 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 231 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 232 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 233 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
zoomMin  = 2.5f;
#line 234 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 235 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 238 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CPlacement3D pl  = ((CPlayerEntity  &) * m_penOwner ) . en_plViewpoint ;
#line 239 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
BOOL bFollowCrossHair ;
#line 241 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(m_iViewType  == VT_3RDPERSONVIEW  || m_iViewType  == VT_PLAYERDEATH )
#line 242 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 245 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  = 5.0f;
#line 247 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
int  WheelDelta  = abs  (_pInput  -> m_WheelPos ) / 120;
#line 248 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> m_WheelPos  > 0 || _pInput  -> GetInputDevice  (1) -> id_aicControls  [ KID_PAGEUP  ] . ic_fValue  == 1.0f)
#line 249 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 251 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> GetInputDevice  (1) -> id_aicControls  [ KID_PAGEUP  ] . ic_fValue  == 1.0f)
#line 252 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 253 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
WheelDelta  = 1.0f;
#line 254 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 255 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  > zoomMin )
#line 256 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 257 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  <= - 1.6)
#line 258 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 260 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  -= 0.2f * WheelDelta ;
#line 261 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 262 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 263 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 264 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  -= 2.0f * WheelDelta ;
#line 265 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 267 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  < zoomMin )
#line 268 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 269 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  = zoomMin ;
#line 271 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 273 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> m_WheelPos  = 0;
#line 274 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 275 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 276 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 277 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fSmooth  > 0.0f && ! bLimitIn ){fSmooth  -= 0.03f;}
#line 278 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fSmooth  <= 0.0f){
#line 279 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fSmooth  = 0.0f;
#line 280 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> m_WheelPos  = 0;
#line 281 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(WheelDelta  > 1){
#line 282 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  = zoomMin  - 1.0f;
#line 283 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fSmooth  = 1.0f;
#line 284 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
bLimitIn  = TRUE ;
#line 286 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 287 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 289 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 292 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(((CPlayer  &) * m_penOwner ) . m_bRide  && fDistanceTmp  <= - 1.1)
#line 293 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 294 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(((CPlayer  &) * m_penOwner ) . m_iRideType  % 2 != 0)
#line 295 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 296 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  = - 1.1f;
#line 297 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 298 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 299 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 300 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else if(_pInput  -> m_WheelPos  < 0 || _pInput  -> GetInputDevice  (1) -> id_aicControls  [ KID_PAGEDOWN  ] . ic_fValue  == 1.0f)
#line 301 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 303 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(bLimitIn ){fDistanceTmp  = zoomMin ;}
#line 304 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
bLimitIn  = FALSE ;
#line 305 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fSmooth  < 0.9f){fSmooth  += 0.1f;}
#line 306 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else if(fSmooth  > 0.9f){
#line 307 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fSmooth  = 0.9f;
#line 308 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 309 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> GetInputDevice  (1) -> id_aicControls  [ KID_PAGEDOWN  ] . ic_fValue  == 1.0f)
#line 310 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 311 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
WheelDelta  = 1.0f;
#line 312 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 314 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  < fDistanceLimit )
#line 315 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 316 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  <= - 1.6)
#line 317 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 319 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  += 0.2f * WheelDelta ;
#line 320 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 321 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 322 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 324 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  += 0.4f * WheelDelta ;
#line 325 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 328 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> m_WheelPos  = 0;
#line 329 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 331 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 333 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  > fDistanceLimit )
#line 334 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 335 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  = fDistanceLimit ;
#line 336 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 337 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  < zoomMin  - 1.0f)
#line 338 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 339 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  = zoomMin  - 1.0f;
#line 340 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 343 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  = fDistance  + fDistanceTmp ;
#line 345 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
bFollowCrossHair  = TRUE ;
#line 347 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 352 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CPlacement3D plTmp ;
#line 353 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
plTmp  = m_penOwner  -> GetLerpedPlacement  ();
#line 354 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
plTmp  . pl_OrientationAngle  (1) = pl  . pl_OrientationAngle  (1);
#line 356 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . RelativeToAbsolute  (plTmp );
#line 359 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vBase ;
#line 360 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
EntityInfo  * pei  = (EntityInfo  *) (m_penOwner  -> GetEntityInfo  ());
#line 368 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vBase  = m_penOwner  -> GetPlacement  () . pl_PositionVector ;
#line 370 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOATmatrix3D mRotation ;
#line 372 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
MakeRotationMatrixFast  (mRotation  , m_penOwner  -> GetPlacement  () . pl_OrientationAngle );
#line 373 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vBase  += FLOAT3D (pei  -> vTargetCenter  [ 0 ] , pei  -> vTargetCenter  [ 1 ] , pei  -> vTargetCenter  [ 2 ]) * mRotation ;
#line 378 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOATmatrix3D m ;
#line 380 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
MakeRotationMatrixFast  (m  , pl  . pl_OrientationAngle );
#line 383 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vRight  = m  . GetColumn  (1);
#line 384 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vUp  = m  . GetColumn  (2);
#line 385 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vFront  = m  . GetColumn  (3);
#line 388 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vDest  [ 5 ];
#line 389 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 0 ] = vBase  + vFront  * fDistance  + vUp  * 1.5f;
#line 390 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 1 ] = vBase  + vFront  * fDistance  + vRight  * 1.5f;
#line 391 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 2 ] = vBase  + vFront  * fDistance  - vRight  * 1.5f;
#line 392 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 3 ] = vBase  + vFront  * fDistance  - vUp  * 1.5f;
#line 393 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 4 ] = vBase  + vFront  * fDistance ;
#line 395 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fBack  = 0;
#line 397 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 399 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
for(INDEX i  = 0;i  < 5;i  ++)
#line 400 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 402 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CCastRay  crRay  (m_penOwner  , vBase  , vDest  [ i  ]);
#line 403 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
crRay  . cr_bHitTranslucentPortals  = FALSE ;
#line 407 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
crRay  . cr_ttHitModels  = CCastRay  :: TT_NONE ;
#line 413 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
GetWorld  () -> CastRay  (crRay );
#line 416 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(crRay  . cr_penHit  != NULL  && (! (crRay  . cr_penHit  -> GetFlags  () & ENF_ALIVE ) && ! (crRay  . cr_penHit  -> GetFlags  () & ENF_ITEM )))
#line 417 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 419 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  = Min  (fDistance  , crRay  . cr_fHitDistance  - 0.5f);
#line 422 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(crRay  . cr_pbpoBrushPolygon  != NULL )
#line 423 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 425 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vDir  = (vDest  [ i  ] - vBase ) . Normalize  ();
#line 428 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fD  = Abs  (FLOAT3D (crRay  . cr_pbpoBrushPolygon  -> bpo_pbplPlane  -> bpl_plAbsolute ) % vDir ) * 0.25f;
#line 429 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fBack  = Max  (fBack  , fD );
#line 430 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
bHit  = TRUE ;
#line 431 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 432 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 433 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 434 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 437 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(((CPlayer  &) * m_penOwner ) . m_bRide )
#line 438 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 439 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(((CPlayer  &) * m_penOwner ) . m_iRideType  % 2 == 0)
#line 440 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 441 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  -= 5.0f;
#line 442 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 443 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 444 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 445 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  -= 4.5f;
#line 446 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 447 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 449 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  = ClampDn  (fDistance  - fBack  , 0.0f);
#line 451 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(m_fDistance  < fDistance )
#line 452 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 453 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_fDistance  += 0.5f;
#line 454 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 456 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(m_fDistance  >= fDistance )
#line 457 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 458 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_fDistance  = fDistance ;
#line 459 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 461 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vBase  += vFront  * m_fDistance ;
#line 462 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  = vBase ;
#line 463 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pNetwork  -> MyCharacterInfo  . m_ModelColor  > 0)
#line 464 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 465 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  (2) += m_fCameraHeight ;
#line 466 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 471 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(m_fDistance  < 1.0f)
#line 472 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 473 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(! m_bPrevModelColor )
#line 474 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 475 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_PrevModelColor  = ((CPlayer  &) * m_penOwner ) . GetModelInstance  () -> GetModelColor  ();
#line 476 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
COLOR tColor  = m_PrevModelColor ;
#line 477 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
tColor  &= 0xFFFFFF00;
#line 478 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
tColor  |= 0x0F;
#line 479 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
((CPlayer  &) * m_penOwner ) . GetModelInstance  () -> mi_colModelColor  = tColor ;
#line 480 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_bPrevModelColor  = TRUE ;
#line 481 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 482 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 483 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 484 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 485 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(m_bPrevModelColor )
#line 486 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 487 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
((CPlayer  &) * m_penOwner ) . GetModelInstance  () -> mi_colModelColor  = m_PrevModelColor ;
#line 488 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_bPrevModelColor  = FALSE ;
#line 489 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 490 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 495 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(((CPlayer  &) * m_penOwner ) . m_bRide )
#line 496 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 497 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(((CPlayer  &) * m_penOwner ) . m_iRideType  % 2 == 0)
#line 498 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 499 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vBase  += vFront  * m_fDistance ;
#line 500 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  = vBase ;
#line 501 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  (2) += 1.0f;
#line 502 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 503 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 504 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 505 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vBase  += vFront  * m_fDistance ;
#line 506 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  = vBase ;
#line 507 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  (2) += 3.0f;
#line 508 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 509 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 510 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(! _pNetwork  -> m_bSingleMode )
#line 511 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 514 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  (2) += fSmooth ;
#line 515 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 520 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetPlacement_special  (pl  , m  , SPIF_NEAR );
#line 521 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}

#line 523 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
void CPlayerView::SetCameraFreeMode() 
#line 524 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 525 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CPlacement3D pl  = GetPlacement  ();
#line 526 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_plNew  = pl ;
#line 528 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fFB  = 0.0f;
#line 529 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fLR  = 0.0f;
#line 530 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fUD  = 0.0f;
#line 531 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fRLR  = 0.0f;
#line 532 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fRUD  = 0.0f;
#line 534 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> GetInput  (FALSE );
#line 536 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> m_WheelPos  > 0)
#line 537 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 538 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> inp_fSpeedMultiplier  += 0.1f;
#line 540 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> inp_fSpeedMultiplier  > 3.0f)
#line 541 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 542 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> inp_fSpeedMultiplier  = 3.0f;
#line 543 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 545 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> m_WheelPos  = 0;
#line 546 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 547 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else if(_pInput  -> m_WheelPos  < 0)
#line 548 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 549 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> inp_fSpeedMultiplier  -= 0.1f;
#line 551 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> inp_fSpeedMultiplier  < 0.0f)
#line 552 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 553 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> inp_fSpeedMultiplier  = 0.0f;
#line 554 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 556 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> m_WheelPos  = 0;
#line 557 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 559 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(BOOL (_pInput  -> GetControlValue  (GetControlGID  (DT_MOUSE  , CID_MOUSE_BUTTON2 ))))
#line 560 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 561 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fFB  = - 1.0f * _pInput  -> inp_fSpeedMultiplier ;
#line 562 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 563 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else if(BOOL (_pInput  -> GetControlValue  (GetControlGID  (DT_MOUSE  , CID_MOUSE_BUTTON1 ))))
#line 564 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 565 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fFB  = + 1.0f * _pInput  -> inp_fSpeedMultiplier ;
#line 566 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 568 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> GetInput  (TRUE );
#line 577 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_OrientationAngle  = m_FreePosition  . pl_OrientationAngle ;
#line 578 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . Translate_OwnSystem  (FLOAT3D (fLR  , fUD  , fFB ));
#line 581 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOATmatrix3D m ;
#line 583 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
MakeRotationMatrixFast  (m  , pl  . pl_OrientationAngle );
#line 584 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetPlacement_special  (pl  , m  , SPIF_NEAR );
#line 597 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}

#line 599 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
void CPlayerView::SetCameraDecoMode() 
#line 600 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 601 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fDistance  = m_fFaceChangeDistance ;
#line 602 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CPlacement3D pl  = ((CPlayerEntity  &) * m_penOwner ) . en_plViewpoint ;
#line 605 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CPlacement3D plTmp  = m_penOwner  -> GetLerpedPlacement  ();
#line 606 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
plTmp  . pl_OrientationAngle  (1) = pl  . pl_OrientationAngle  (1);
#line 607 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . RelativeToAbsolute  (plTmp );
#line 610 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOATmatrix3D m ;
#line 611 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
MakeRotationMatrixFast  (m  , pl  . pl_OrientationAngle );
#line 614 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vBase  = m_penOwner  -> GetPlacement  () . pl_PositionVector ;
#line 615 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vFront  = m  . GetColumn  (3);
#line 616 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vBase  += vFront  * fDistance ;
#line 618 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  = vBase ;
#line 621 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  (2) += m_fCameraHeight ;
#line 623 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetPlacement_special  (pl  , m  , SPIF_NEAR );
#line 625 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}

#line 627 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
void CPlayerView::SetCameraPosition() 
#line 628 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 630 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fDistance  = 1.0f;
#line 631 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
static FLOAT fDistanceTmp  = 0.0f;
#line 632 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
static FLOAT fUpTmp  = 0.0f;
#line 634 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CPlacement3D pl  = ((CPlayerEntity  &) * m_penOwner ) . en_plViewpoint ;
#line 635 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
BOOL bFollowCrossHair ;
#line 638 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
extern  BOOL _bWorldEditorApp ;
#line 642 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
BOOL bBackView  = TRUE ;
#line 645 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(m_iViewType  == VT_3RDPERSONVIEW  || m_iViewType  == VT_PLAYERDEATH )
#line 646 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 648 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pNetwork  -> m_bSingleMode )
#line 649 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 650 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  = 6.0f;
#line 651 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 652 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 653 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 654 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  = 5.0f;
#line 655 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 657 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> GetInputDevice  (1) -> id_aicControls  [ KID_PAGEUP  ] . ic_fValue  == 1.0f)
#line 658 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 659 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fUpTmp  -= 10.0f;
#line 660 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_bLockRotate  = TRUE ;
#line 661 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 662 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> GetInputDevice  (1) -> id_aicControls  [ KID_PAGEDOWN  ] . ic_fValue  == 1.0f)
#line 663 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 664 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fUpTmp  += 10.0f;
#line 665 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_bLockRotate  = TRUE ;
#line 666 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 670 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> m_WheelPos  > 0){
#line 671 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  > - 3.6f){
#line 672 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  <= - 1.6){
#line 673 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  -= 0.2f;
#line 674 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 675 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 676 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 677 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  -= 1.0f;
#line 678 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 680 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> m_WheelPos  = 0;
#line 681 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 682 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 683 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else if(_pInput  -> m_WheelPos  < 0){
#line 684 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  < 25.0f){
#line 685 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(fDistanceTmp  <= - 1.6){
#line 686 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  += 0.2f;
#line 687 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 688 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 689 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 690 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  += 1.0f;
#line 691 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 693 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> m_WheelPos  = 0;
#line 694 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 695 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 697 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pNetwork  -> m_bSingleMode )
#line 698 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 699 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistanceTmp  = 0.0f;
#line 700 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 702 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  = fDistance  + fDistanceTmp ;
#line 704 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
bFollowCrossHair  = TRUE ;
#line 706 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 708 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_OrientationAngle  (3) = 0.0f;
#line 713 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CPlacement3D plTmp ;
#line 714 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
plTmp  = m_penOwner  -> GetPlacement  ();
#line 717 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . RelativeToAbsolute  (plTmp );
#line 718 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . RelativeToAbsolute  (m_penOwner  -> GetPlacement  ());
#line 720 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vBase ;
#line 721 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
EntityInfo  * pei  = (EntityInfo  *) (m_penOwner  -> GetEntityInfo  ());
#line 724 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pNetwork  -> m_bSingleMode  && bBackView )
#line 725 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 726 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CPlayerWeapons  * ppw  = ((CPlayer  &) * m_penOwner ) . GetPlayerWeapons  ();
#line 727 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT m_fCurTime  = _pTimer  -> CurrentTick  ();
#line 729 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(! m_bLockRotate )
#line 730 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 732 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(ppw  -> m_penRayHitTmp )
#line 733 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 734 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vDelta  = ppw  -> m_vRayHitTmp  - m_penOwner  -> GetPlacement  () . pl_PositionVector ;
#line 735 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDelta  . SafeNormalize  ();
#line 736 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
ANGLE aDelta  = GetRelativeHeading  (vDelta );
#line 737 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
aDelta  = NormalizeAngle  (aDelta );
#line 739 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(! m_bInit )
#line 740 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 741 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_bInit  = TRUE ;
#line 742 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_fLastTime  = m_fCurTime ;
#line 743 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 744 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_aVelocity  = aDelta ;
#line 745 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 746 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT m_fDeltaTime  = m_fCurTime  - m_fLastTime ;
#line 747 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_aVelocity  = m_aVelocity  + (m_aAccel  * m_fDeltaTime );
#line 748 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_aCurAngle  = m_aCurAngle  + (m_aVelocity  * m_fDeltaTime );
#line 749 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 751 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_fLastTime  = m_fCurTime ;
#line 753 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_OrientationAngle  (1) = m_aCurAngle  - fUpTmp ;
#line 754 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 762 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vBase  = m_penOwner  -> GetLerpedPlacement  () . pl_PositionVector ;
#line 764 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOATmatrix3D mRotation ;
#line 766 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
MakeRotationMatrixFast  (mRotation  , m_penOwner  -> GetPlacement  () . pl_OrientationAngle );
#line 767 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vBase  += FLOAT3D (pei  -> vTargetCenter  [ 0 ] , pei  -> vTargetCenter  [ 1 ] , pei  -> vTargetCenter  [ 2 ]) * mRotation ;
#line 772 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOATmatrix3D m ;
#line 775 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
MakeRotationMatrixFast  (m  , pl  . pl_OrientationAngle );
#line 778 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vRight  = m  . GetColumn  (1);
#line 779 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vUp  = m  . GetColumn  (2);
#line 780 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vFront  = m  . GetColumn  (3);
#line 783 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vDest  [ 5 ];
#line 784 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 0 ] = vBase  + vFront  * fDistance  + vUp  * 1.0f;
#line 785 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 1 ] = vBase  + vFront  * fDistance  - vUp  * 1.0f;
#line 786 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 2 ] = vBase  + vFront  * fDistance  + vRight  * 1.0f;
#line 787 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 3 ] = vBase  + vFront  * fDistance  - vRight  * 1.0f;
#line 788 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vDest  [ 4 ] = vBase  + vFront  * fDistance ;
#line 790 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fBack  = 0;
#line 792 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
for(INDEX i  = 0;i  < 5;i  ++)
#line 793 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 795 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
CCastRay  crRay  (m_penOwner  , vBase  , vDest  [ i  ]);
#line 796 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
crRay  . cr_bHitTranslucentPortals  = FALSE ;
#line 797 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
crRay  . cr_ttHitModels  = CCastRay  :: TT_COLLISIONBOX ;
#line 798 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
GetWorld  () -> CastRay  (crRay );
#line 801 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(crRay  . cr_penHit  != NULL  && (! (crRay  . cr_penHit  -> GetFlags  () & ENF_ALIVE ) && ! (crRay  . cr_penHit  -> GetFlags  () & ENF_ITEM )))
#line 802 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 804 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  = Min  (fDistance  , crRay  . cr_fHitDistance  - 0.5f);
#line 806 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(crRay  . cr_pbpoBrushPolygon  != NULL )
#line 807 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 809 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT3D vDir  = (vDest  [ i  ] - vBase ) . Normalize  ();
#line 836 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
FLOAT fD  = Abs  (FLOAT3D (crRay  . cr_pbpoBrushPolygon  -> bpo_pbplPlane  -> bpl_plAbsolute ) % vDir ) * 0.25f;
#line 837 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fBack  = Max  (fBack  , fD );
#line 840 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 841 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 842 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 844 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
fDistance  = ClampDn  (fDistance  - fBack  , 0.0f);
#line 845 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_fDistance  = fDistance ;
#line 846 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
vBase  += vFront  * fDistance ;
#line 883 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  = vBase ;
#line 898 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetPlacement_special  (pl  , m  , SPIF_NEAR );
#line 899 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
BOOL CPlayerView::
#line 902 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPlayerView_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EViewInit, "CPlayerView::Main expects 'EViewInit' as input!");	const EViewInit &eInit = (const EViewInit &)__eeInput;
#line 905 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
ASSERT  (((CEntity  *) eInit  . eidOwner ) != NULL );
#line 906 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_penOwner  = eInit  . eidOwner ;
#line 908 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_iViewType  = VT_3RDPERSONVIEW ;
#line 909 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_bFixed  = eInit  . bDeathFixed ;
#line 910 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
ASSERT  (IsOfClass  (m_penOwner  , & CPlayer_DLLClass ));
#line 913 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
InitAsEditorModel  ();
#line 914 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetFlags  (GetFlags  () | ENF_CROSSESLEVELS );
#line 915 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL  | EPF_MOVABLE );
#line 916 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 918 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetFlagOff  (ENF_PLACCHANGED  | ENF_PROPSCHANGED );
#line 919 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetFlagOff  (ENF_PROPSCHANGED );
#line 922 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetModel  (MODEL_MARKER );
#line 923 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetModelMainTexture  (TEXTURE_MARKER );
#line 931 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_bLockRotate  = FALSE ;
#line 933 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SendEvent  (EStart  ());
#line 934 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01930001, FALSE, EBegin());return TRUE;}BOOL CPlayerView::H0x01930001_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01930001
switch(__eeInput.ee_slEvent)
#line 935 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{case(EVENTCODE_EBegin):
#line 937 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{const EBegin&e= (EBegin&)__eeInput;

#line 938 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
return TRUE;
#line 939 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):
#line 941 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{const EStart&e= (EStart&)__eeInput;

#line 945 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(m_bUseTraceMode )
#line 946 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 948 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetCameraPosition  ();
#line 949 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 951 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 952 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 953 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
SetCameraPositionEx  ();
#line 954 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 955 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
en_plLastPlacement  = GetPlacement  ();
#line 956 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_vTargetLast  = ((CPlayer  &) * m_penOwner ) . GetPlayerWeapons  () -> m_vRayHit ;
#line 957 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
return TRUE;
#line 958 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}ASSERT(FALSE);break;case(EVENTCODE_EEnd):{const EEnd&e= (EEnd&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01930002, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETrigger):
#line 961 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{const ETrigger&e= (ETrigger&)__eeInput;

#line 962 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
_pInput  -> inp_bFreeMode  = ! _pInput  -> inp_bFreeMode ;
#line 963 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
if(_pInput  -> inp_bFreeMode )
#line 964 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 965 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
m_FreePosition  = GetPlacement  ();
#line 966 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
while(ShowCursor  (FALSE ) >= 0){};
#line 967 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 968 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
else 
#line 969 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
{
#line 970 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
while(ShowCursor  (TRUE ) < 0){};
#line 971 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}
#line 973 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
return TRUE;
#line 974 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 976 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
}return TRUE;}BOOL CPlayerView::H0x01930002_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01930002

#line 978 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
Destroy  (FALSE );
#line 980 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
Return(STATE_CURRENT,EVoid());
#line 980 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/PlayerView.es"
return TRUE; ASSERT(FALSE); return TRUE;};