/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"

#include "StdH.h"

#include <Switch.h>
#include <Switch_tables.h>
CEntityEvent *EFlipTheSwitch::MakeCopy(void) { 	CEntityEvent *peeCopy = new EFlipTheSwitch(*this); 	return peeCopy;}
SLONG EFlipTheSwitch::GetSizeOf(void) { 	return sizeof(*this);}
EFlipTheSwitch::EFlipTheSwitch() : CEntityEvent(EVENTCODE_EFlipTheSwitch) {
	ClearToDefault(iState);
	ClearToDefault(iUseable);
}
BOOL EFlipTheSwitch::CheckIDs(void) {	return TRUE ; }

void CSwitch::SetDefaultProperties(void) {
	m_iModelONAnimation = 0;
	m_iTextureONAnimation = 0;
	m_iModelOFFAnimation = 0;
	m_iTextureOFFAnimation = 0;
	m_penTarget = NULL;
	m_eetEvent = EET_START ;
	m_eetOffEvent = EET_IGNORE ;
	m_penOffTarget = NULL;
	m_swtType = SWT_ONOFF ;
	m_strMessage = "";
	m_bSwitchON = FALSE ;
	m_penCaused = NULL;
	m_bUseable = FALSE ;
	m_bInvisible = FALSE ;
	CModelHolder2::SetDefaultProperties();
}

#line 51 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
BOOL CSwitch::HandleEvent(const CEntityEvent & ee) 
#line 52 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
{
#line 53 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(ee  . ee_slEvent  == EVENTCODE_EFlipTheSwitch ){
#line 54 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(! _pNetwork  -> IsServer  ()){
#line 55 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
EFlipTheSwitch  & efts  = (EFlipTheSwitch  &) ee ;
#line 56 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = efts  . iUseable ;
#line 57 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(efts  . iState  != m_bSwitchON ){
#line 58 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(efts  . iState ){
#line 60 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
GetModelObject  () -> PlayAnim  (m_iModelONAnimation  , 0);
#line 61 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
GetModelObject  () -> mo_toTexture  . PlayAnim  (m_iTextureONAnimation  , 0);
#line 62 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bSwitchON  = TRUE ;
#line 63 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}else {
#line 65 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
GetModelObject  () -> PlayAnim  (m_iModelOFFAnimation  , 0);
#line 66 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
GetModelObject  () -> mo_toTexture  . PlayAnim  (m_iTextureOFFAnimation  , 0);
#line 67 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bSwitchON  = FALSE ;
#line 68 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 69 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 70 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 71 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE ;
#line 72 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 74 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return CModelHolder2  :: HandleEvent  (ee );
#line 75 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}

#line 78 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
CAnimData * CSwitch::GetAnimData(SLONG slPropertyOffset) 
#line 79 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
{
#line 80 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(slPropertyOffset  == offsetof  (CSwitch  , m_iModelONAnimation ) || 
#line 81 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
slPropertyOffset  == offsetof  (CSwitch  , m_iModelOFFAnimation )){
#line 82 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return GetModelObject  () -> GetData  ();
#line 83 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}else if(slPropertyOffset  == offsetof  (CSwitch  , m_iTextureONAnimation ) || 
#line 84 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
slPropertyOffset  == offsetof  (CSwitch  , m_iTextureOFFAnimation )){
#line 85 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return GetModelObject  () -> mo_toTexture  . GetData  ();
#line 86 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}else {
#line 87 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return CModelHolder2  :: GetAnimData  (slPropertyOffset );
#line 88 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 89 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}

#line 92 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
BOOL CSwitch::CanReactOnEntity(CEntity * pen) 
#line 93 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
{
#line 94 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(pen  == NULL ){
#line 95 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return FALSE ;
#line 96 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 98 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(! (pen  -> GetFlags  () & ENF_ALIVE )){
#line 99 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return FALSE ;
#line 100 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 102 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE ;
#line 103 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}

#line 107 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SLONG CSwitch::GetUsedMemory(void) 
#line 108 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
{
#line 110 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SLONG  slUsedMemory  = sizeof  (CSwitch ) - sizeof  (CModelHolder2 ) + CModelHolder2  :: GetUsedMemory  ();
#line 112 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
slUsedMemory  += m_strMessage  . Length  ();
#line 113 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return slUsedMemory ;
#line 114 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
BOOL CSwitch::
#line 119 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 121 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
CModelHolder2  :: InitModelHolder  ();
#line 123 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(m_bInvisible ){
#line 124 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SwitchToEditorModel  ();
#line 125 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 127 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(m_swtType  == SWT_ONCE ){
#line 128 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Jump(STATE_CURRENT, STATE_CSwitch_MainLoop_Once, TRUE, EVoid());return TRUE;
#line 129 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}else {
#line 130 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Jump(STATE_CURRENT, STATE_CSwitch_MainLoop_OnOff, TRUE, EVoid());return TRUE;
#line 131 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 133 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EVoid());
#line 133 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CSwitch::
#line 137 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SwitchON(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_SwitchON
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::SwitchON expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 139 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(m_bSwitchON ){
#line 141 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EVoid());
#line 141 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE;
#line 142 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 143 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(_pNetwork  -> IsServer  ()){
#line 144 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
EFlipTheSwitch  efts ;
#line 145 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
efts  . iState  = TRUE ;
#line 146 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
efts  . iUseable  = m_bUseable ;
#line 147 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SendEvent  (efts  , TRUE );
#line 148 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 150 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
GetModelObject  () -> PlayAnim  (m_iModelONAnimation  , 0);
#line 151 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
GetModelObject  () -> mo_toTexture  . PlayAnim  (m_iTextureONAnimation  , 0);
#line 152 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bSwitchON  = TRUE ;
#line 154 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SendToTarget  (m_penTarget  , m_eetEvent  , m_penCaused );
#line 156 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (m_iModelONAnimation ));
Jump(STATE_CURRENT, 0x00d10002, FALSE, EBegin());return TRUE;}BOOL CSwitch::H0x00d10002_SwitchON_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10002
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x00d10003, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;
return FALSE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 158 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}return TRUE;}BOOL CSwitch::H0x00d10003_SwitchON_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10003

#line 160 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EReturn  ());
#line 160 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CSwitch::
#line 164 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SwitchOFF(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_SwitchOFF
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::SwitchOFF expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 166 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(! m_bSwitchON ){
#line 168 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EVoid());
#line 168 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE;
#line 169 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 170 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(_pNetwork  -> IsServer  ()){
#line 171 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
EFlipTheSwitch  efts ;
#line 172 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
efts  . iState  = FALSE ;
#line 173 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
efts  . iUseable  = m_bUseable ;
#line 174 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SendEvent  (efts  , TRUE );
#line 175 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 177 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
GetModelObject  () -> PlayAnim  (m_iModelOFFAnimation  , 0);
#line 178 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
GetModelObject  () -> mo_toTexture  . PlayAnim  (m_iTextureOFFAnimation  , 0);
#line 179 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bSwitchON  = FALSE ;
#line 181 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(m_penOffTarget  != NULL )
#line 182 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
{
#line 183 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SendToTarget  (m_penOffTarget  , m_eetOffEvent  , m_penCaused );
#line 184 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 185 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
else 
#line 186 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
{
#line 188 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SendToTarget  (m_penTarget  , m_eetOffEvent  , m_penCaused );
#line 189 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 191 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (m_iModelOFFAnimation ));
Jump(STATE_CURRENT, 0x00d10005, FALSE, EBegin());return TRUE;}BOOL CSwitch::H0x00d10005_SwitchOFF_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10005
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x00d10006, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;
return FALSE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 193 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}return TRUE;}BOOL CSwitch::H0x00d10006_SwitchOFF_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10006

#line 195 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EReturn  ());
#line 195 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CSwitch::
#line 198 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
MainLoop_Once(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_MainLoop_Once
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::MainLoop_Once expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 199 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = TRUE ;
#line 202 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00d10008, FALSE, EBegin());return TRUE;}BOOL CSwitch::H0x00d10008_MainLoop_Once_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10008
switch(__eeInput.ee_slEvent){case(EVENTCODE_ETrigger):{const ETrigger&eTrigger= (ETrigger&)__eeInput;

#line 205 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(CanReactOnEntity  (eTrigger  . penCaused ) && m_bUseable ){
#line 206 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 207 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_penCaused  = eTrigger  . penCaused ;
#line 208 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchON, TRUE, EVoid());return TRUE;
#line 209 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 210 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;

#line 213 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 214 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchON, TRUE, EVoid());return TRUE;
#line 215 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):{const EStop&e= (EStop&)__eeInput;

#line 218 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 219 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchOFF, TRUE, EVoid());return TRUE;
#line 220 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EReturn):{const EReturn&e= (EReturn&)__eeInput;

#line 222 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = ! m_bSwitchON ;
#line 223 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(_pNetwork  -> IsServer  ()){
#line 224 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
EFlipTheSwitch  efts ;
#line 225 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
efts  . iState  = m_bSwitchON ;
#line 226 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
efts  . iUseable  = m_bUseable ;
#line 227 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SendEvent  (efts  , TRUE );
#line 228 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 229 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE;
#line 230 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 231 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}return TRUE;}BOOL CSwitch::H0x00d10009_MainLoop_Once_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10009
 ASSERT(FALSE); return TRUE;};BOOL CSwitch::
#line 234 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
MainLoop_OnOff(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_MainLoop_OnOff
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::MainLoop_OnOff expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 235 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = TRUE ;
#line 238 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00d1000b, FALSE, EBegin());return TRUE;}BOOL CSwitch::H0x00d1000b_MainLoop_OnOff_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d1000b
switch(__eeInput.ee_slEvent){case(EVENTCODE_ETrigger):{const ETrigger&eTrigger= (ETrigger&)__eeInput;

#line 241 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(CanReactOnEntity  (eTrigger  . penCaused ) && m_bUseable ){
#line 242 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 243 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_penCaused  = eTrigger  . penCaused ;
#line 245 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(m_bSwitchON ){
#line 246 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchOFF, TRUE, EVoid());return TRUE;
#line 248 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}else {
#line 249 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchON, TRUE, EVoid());return TRUE;
#line 250 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 251 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 252 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE;
#line 253 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;

#line 256 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 257 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchON, TRUE, EVoid());return TRUE;
#line 258 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):{const EStop&e= (EStop&)__eeInput;

#line 261 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 262 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchOFF, TRUE, EVoid());return TRUE;
#line 263 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;

#line 266 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(m_penDestruction  != NULL ){
#line 267 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
Jump(STATE_CURRENT, STATE_CModelHolder2_Die, FALSE, EVoid());return TRUE;
#line 268 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 269 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE;
#line 270 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EReturn):{const EReturn&e= (EReturn&)__eeInput;

#line 272 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
m_bUseable  = TRUE ;
#line 273 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
if(_pNetwork  -> IsServer  ()){
#line 274 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
EFlipTheSwitch  efts ;
#line 275 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
efts  . iState  = m_bSwitchON ;
#line 276 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
efts  . iUseable  = m_bUseable ;
#line 277 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
SendEvent  (efts  , TRUE );
#line 278 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}
#line 279 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
return TRUE;
#line 280 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 281 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Switch.es"
}return TRUE;}BOOL CSwitch::H0x00d1000c_MainLoop_OnOff_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d1000c
 ASSERT(FALSE); return TRUE;};