/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"

#include "StdH.h"

#include <Unit.h>
#include <Unit_tables.h>
void CUnit::SetDefaultProperties(void) {
	m_ttTarget = TT_NONE ;
	m_strName = "Unit";
	m_fMaxHealth = -1.0f;
	m_nMaxiHealth = 0;
	m_nCurrentHealth = 0;
	m_nMobLevel = 0;
	m_nPreHealth = -1;
	m_nMobDBIndex = -1;
	m_fActivityRange = 0.0f;
	m_fAttackRadius = 10000.0f;
	m_dtDestination = DT_PLAYERCURRENT ;
	m_fWalkSpeed = 1.0f;
	m_aWalkRotateSpeed = AngleDeg(10.0f);
	m_fAttackRunSpeed = 1.0f;
	m_aAttackRotateSpeed = AngleDeg(10.0f);
	m_fCloseRunSpeed = 1.0f;
	m_aCloseRotateSpeed = AngleDeg(10.0f);
	m_fAttackDistance = 3.0f;
	m_fCloseDistance = 0.0f;
	m_fAttackFireTime = 2.0f;
	m_fCloseFireTime = 2.0f;
	m_fStopDistance = 0.5f;
	m_fIgnoreRange = 50.0f;
	m_fMoveTime = 0.0f;
	m_fMoveSpeed = 0.0f;
	m_aRotateSpeed = 0.0f;
	m_fMoveFrequency = 0.0f;
	m_fSenseRange = 0.0f;
	m_fViewAngle = 360.0f;
	m_fFallHeight = 8.0f;
	m_fStepHeight = -1.0f;
	m_fShootTime = 0.0f;
	m_fDamageConfused = 0.0f;
	m_fBlowUpAmount = 0.0f;
	m_fBodyParts = 4;
	m_fDamageWounded = 0.0f;
	m_nPlayActionNum = -1;
	m_vDesiredPosition = FLOAT3D(0 , 0 , 0);
	m_bSkilling = FALSE ;
	m_nCurrentSkillNum = -1;
	m_fSkillSpeed = 1.0f;
	m_fAttackLengthMul = 1.0f;
	m_fAttackSpeedMul = 1.0f;
	m_idCurrentSkillAnim = -1;
	m_bAttack = FALSE ;
	m_bWasKilled = FALSE ;
	m_bUseAI = FALSE ;
	m_bAIStart = FALSE ;
	m_tmSkillStartTime = 0.0f;
	m_tmSkillAnimTime = 0.0f;
	m_fSkillAnimTime = 0.0f;
	m_bKillEnemy = FALSE ;
	m_vMyPositionTmp = FLOAT3D(0.0f , 0.0f , 0.0f);
	m_enAttackerID = 0;
	m_bStuned = FALSE ;
	m_bHold = FALSE ;
	m_bCannotUseSkill = FALSE ;
	CMovableModelEntity::SetDefaultProperties();
}
void CUnit::OnInitialize(const CEntityEvent & eeInput) 
#line 131 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 132 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
CMovableModelEntity  :: OnInitialize  (eeInput );
#line 133 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
void CUnit::OnEnd(void) 
#line 136 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 137 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
m_dcEnemies  . Clear  ();
#line 138 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
CMovableModelEntity  :: OnEnd  ();
#line 139 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
void CUnit::DeathNow() {}
void CUnit::SkillNow() {}
void CUnit::PreSkillNow() {}
void CUnit::AttackNow() {}
void CUnit::ActionNow() {}
void CUnit::SetAttackSpeed(SBYTE attackspeed) {}
void CUnit::StopNow() {}
BOOL CUnit::SetTargetEntity(CEntity * penPlayer) {return TRUE ;}
BOOL CUnit::SetKillTargetEntity(CEntity * penKill) {return FALSE ;}
BOOL CUnit::SetEnemyEntity(CEntity * penEnemy,int type) {return TRUE ;}
void CUnit::SetNoTargetEntity(void) {}
void CUnit::StopandTeleport() {}
void CUnit::MoveNow() {}
void CUnit::SendActEvent(void) {}
BOOL CUnit::CheckTarget(CEntity * penTarget) {return FALSE ;}
BOOL CUnit::UseSkill(int iSkillIndex) {return FALSE ;}
BOOL CUnit::IsMovable() {return TRUE ;}
BOOL CUnit::IsAvailableRide() {return FALSE ;}
void CUnit::StopMove() 
#line 163 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 164 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(_pNetwork  -> m_bSingleMode )
#line 165 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 166 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
_pNetwork  -> SendStopMessage  (this  , GetPlacement  ());
#line 167 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 168 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
m_vDesiredPosition  = GetPlacement  () . pl_PositionVector ;
#line 169 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
m_vMyPositionTmp  = GetPlacement  () . pl_PositionVector ;
#line 170 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
StopRotating  ();
#line 171 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
StopTranslating  ();
#line 172 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
FLOAT & CUnit::GetProp(FLOAT & m_fBase) 
#line 181 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 182 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return m_fBase ;
#line 183 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
FLOAT CUnit::GetThreatDistance(void) 
#line 187 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 189 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return Max  (GetProp  (m_fCloseDistance ) , GetProp  (m_fStopDistance ));
#line 190 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 193 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D CUnit::CalcDelta(CEntity * penEntity) 
#line 194 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 195 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ASSERT  (penEntity  != NULL );
#line 197 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return penEntity  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 198 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 201 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT CUnit::CalcDist(CEntity * penEntity) 
#line 202 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 203 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return CalcDelta  (penEntity ) . Length  ();
#line 204 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 207 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D CUnit::CalcPlaneDelta(CEntity * penEntity) 
#line 208 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 209 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ASSERT  (penEntity  != NULL );
#line 210 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vPlaneDelta ;
#line 212 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
GetNormalComponent  (
#line 213 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
penEntity  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector  , 
#line 214 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
en_vGravityDir  , vPlaneDelta );
#line 215 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return vPlaneDelta ;
#line 216 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 219 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT CUnit::CalcPlaneDist(CEntity * penEntity) 
#line 220 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 221 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return CalcPlaneDelta  (penEntity ) . Length  ();
#line 222 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 225 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT CUnit::GetFrustumAngle(const FLOAT3D & vDir) 
#line 226 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 228 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vFront  = - GetRotationMatrix  () . GetColumn  (3);
#line 230 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return (vDir  / vDir  . Length  ()) % vFront ;
#line 231 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 234 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT CUnit::GetPlaneFrustumAngle(const FLOAT3D & vDir) 
#line 235 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 236 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vPlaneDelta ;
#line 238 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
GetNormalComponent  (vDir  , en_vGravityDir  , vPlaneDelta );
#line 240 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vFront  = - GetRotationMatrix  () . GetColumn  (3);
#line 241 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vPlaneFront ;
#line 242 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
GetNormalComponent  (vFront  , en_vGravityDir  , vPlaneFront );
#line 244 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vPlaneDelta  . SafeNormalize  ();
#line 245 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vPlaneFront  . SafeNormalize  ();
#line 246 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return vPlaneDelta  % vPlaneFront ;
#line 247 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 250 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
BOOL CUnit::IsInFrustum(CEntity * penEntity,FLOAT fCosHalfFrustum) 
#line 251 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 253 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vDelta  = CalcDelta  (penEntity );
#line 255 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vFront  = - GetRotationMatrix  () . GetColumn  (3);
#line 257 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT fDotProduct  = (vDelta  / vDelta  . Length  ()) % vFront ;
#line 258 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return fDotProduct  >= fCosHalfFrustum ;
#line 259 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 262 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
BOOL CUnit::IsInPlaneFrustum(CEntity * penEntity,FLOAT fCosHalfFrustum) 
#line 263 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 265 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vPlaneDelta  = CalcPlaneDelta  (penEntity );
#line 267 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vFront  = - GetRotationMatrix  () . GetColumn  (3);
#line 268 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vPlaneFront ;
#line 269 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
GetNormalComponent  (vFront  , en_vGravityDir  , vPlaneFront );
#line 271 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vPlaneDelta  . SafeNormalize  ();
#line 272 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vPlaneFront  . SafeNormalize  ();
#line 273 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT fDot  = vPlaneDelta  % vPlaneFront ;
#line 274 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return fDot  >= fCosHalfFrustum ;
#line 275 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 278 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
BOOL CUnit::IsVisible(CEntity * penEntity) 
#line 279 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 280 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ASSERT  (penEntity  != NULL );
#line 282 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vSource  , vTarget ;
#line 283 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
GetPositionCastRay  (this  , penEntity  , vSource  , vTarget );
#line 286 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
CCastRay  crRay  (this  , vSource  , vTarget );
#line 287 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
crRay  . cr_ttHitModels  = CCastRay  :: TT_NONE ;
#line 288 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
crRay  . cr_bHitTranslucentPortals  = FALSE ;
#line 289 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
en_pwoWorld  -> CastRay  (crRay );
#line 292 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return (crRay  . cr_penHit  == NULL );
#line 293 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 296 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
BOOL CUnit::IsVisibleCheckAll(CEntity * penEntity) 
#line 297 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 298 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ASSERT  (penEntity  != NULL );
#line 300 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vSource  , vTarget ;
#line 301 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
GetPositionCastRay  (this  , penEntity  , vSource  , vTarget );
#line 304 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
CCastRay  crRay  (this  , vSource  , vTarget );
#line 305 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
crRay  . cr_ttHitModels  = CCastRay  :: TT_COLLISIONBOX ;
#line 306 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
crRay  . cr_bHitTranslucentPortals  = FALSE ;
#line 307 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
en_pwoWorld  -> CastRay  (crRay );
#line 310 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return crRay  . cr_penHit  == penEntity ;
#line 311 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 314 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT CUnit::CalcDistanceInPlaneToDestination(void) 
#line 315 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 317 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vNormal ;
#line 318 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
GetNormalComponent  (m_vDesiredPosition  - GetPlacement  () . pl_PositionVector  , en_vGravityDir  , vNormal );
#line 319 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return vNormal  . Length  ();
#line 320 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
ULONG CUnit::SetDesiredMovementEx(void) 
#line 331 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 332 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ULONG  ulFlags  = 0;
#line 335 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vDelta  = m_vDesiredPosition  - GetPlacement  () . pl_PositionVector ;
#line 336 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vDelta  (2) = 0.0f;
#line 339 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(m_aRotateSpeed  > 0.0f)
#line 340 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 342 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vDir  = vDelta ;
#line 343 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vDir  . SafeNormalize  ();
#line 344 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ANGLE aWantedHeadingRelative  = GetRelativeHeading  (vDir );
#line 347 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
aWantedHeadingRelative  = NormalizeAngle  (aWantedHeadingRelative );
#line 349 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ANGLE aHeadingRotation ;
#line 351 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(aWantedHeadingRelative  < - m_aRotateSpeed  * m_fMoveFrequency )
#line 352 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 354 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
aHeadingRotation  = - m_aRotateSpeed ;
#line 356 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 357 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
else if(aWantedHeadingRelative  > m_aRotateSpeed  * m_fMoveFrequency )
#line 358 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 360 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
aHeadingRotation  = + m_aRotateSpeed ;
#line 362 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 363 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
else 
#line 364 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 366 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
aHeadingRotation  = aWantedHeadingRelative  / m_fMoveFrequency ;
#line 367 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 369 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
SetDesiredRotation  (ANGLE3D (aHeadingRotation  , 0 , 0));
#line 371 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(Abs  (aHeadingRotation ) > 1.0f)
#line 372 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 373 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ulFlags  |= MF_ROTATEH ;
#line 374 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 377 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 378 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
else 
#line 379 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 381 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
SetDesiredRotation  (ANGLE3D (0 , 0 , 0));
#line 382 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 386 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(m_fMoveSpeed  > 0.0f)
#line 387 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 389 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vDelta  = m_vDesiredPosition  - GetPlacement  () . pl_PositionVector ;
#line 390 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vDelta  (2) = 0.0f;
#line 392 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT length  = vDelta  . Length  ();
#line 393 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT deltaX  = m_vDesiredPosition  (1) - GetPlacement  () . pl_PositionVector  (1);
#line 394 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT deltaZ  = m_vDesiredPosition  (3) - GetPlacement  () . pl_PositionVector  (3);
#line 396 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT num  = length  / m_fMoveSpeed ;
#line 399 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(num  < 1.0f)
#line 400 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 402 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vDelta  = GetPlacement  () . pl_PositionVector  - m_vMyPositionTmp ;
#line 403 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vDelta  (2) = 0.0f;
#line 405 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(vDelta  . Length  () < 0.5f)
#line 406 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 408 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT flength  = Sqrt  (deltaX  * deltaX  + deltaZ  * deltaZ );
#line 410 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(flength  < 0.5f)
#line 411 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 412 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(! _pNetwork  -> m_bSingleMode ){
#line 413 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
StopMove  ();
#line 414 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 415 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return 0;
#line 416 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 417 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 419 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
CPlacement3D plPlacement ;
#line 420 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
plPlacement  . pl_OrientationAngle  = ANGLE3D (GetPlacement  () . pl_OrientationAngle  (1) , 0 , 0);
#line 421 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
plPlacement  . pl_PositionVector  = m_vDesiredPosition ;
#line 424 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(! _pNetwork  -> m_bSingleMode )
#line 425 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 426 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
_pNetwork  -> SendMoveMessage  (this  , plPlacement  , m_fMoveSpeed );
#line 427 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 428 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
m_vMyPositionTmp  = GetPlacement  () . pl_PositionVector ;
#line 430 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return SetDesiredMovement  ();
#line 431 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 435 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
deltaX  = deltaX  / num ;
#line 436 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
deltaZ  = deltaZ  / num ;
#line 438 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vRayHit ;
#line 439 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
CPlacement3D plPlacement ;
#line 440 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
plPlacement  . pl_OrientationAngle  = ANGLE3D (0 , 0 , 0);
#line 441 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
plPlacement  . pl_PositionVector  = FLOAT3D (GetPlacement  () . pl_PositionVector  (1) + deltaX  , 300.0f , GetPlacement  () . pl_PositionVector  (3) + deltaZ );
#line 443 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT fMaxY  = - 9999999.0f;
#line 444 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
BOOL bFloorHitted  = FALSE ;
#line 446 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vSource  = plPlacement  . pl_PositionVector ;
#line 447 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vTarget  = vSource ;
#line 448 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vTarget  (2) -= 1000.0f;
#line 449 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
CCastRay  crRay  (this  , vSource  , vTarget );
#line 450 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
crRay  . cr_ttHitModels  = CCastRay  :: TT_NONE ;
#line 451 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
crRay  . cr_bHitTranslucentPortals  = TRUE ;
#line 452 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
crRay  . cr_bPhysical  = TRUE ;
#line 453 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
GetWorld  () -> CastRay  (crRay );
#line 454 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if((crRay  . cr_penHit  != NULL ) && (crRay  . cr_vHit  (2) > fMaxY ))
#line 455 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 456 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
fMaxY  = crRay  . cr_vHit  (2);
#line 457 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
bFloorHitted  = TRUE ;
#line 458 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 460 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(bFloorHitted )
#line 461 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 462 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
plPlacement  . pl_PositionVector  (2) += fMaxY  - plPlacement  . pl_PositionVector  (2) + 0.01f;
#line 463 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 465 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
plPlacement  . pl_OrientationAngle  (1) = GetPlacement  () . pl_OrientationAngle  (1);
#line 468 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(! _pNetwork  -> m_bSingleMode )
#line 469 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 470 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
_pNetwork  -> SendMoveMessage  (this  , plPlacement  , m_fMoveSpeed );
#line 471 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 472 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
m_vMyPositionTmp  = GetPlacement  () . pl_PositionVector ;
#line 474 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return SetDesiredMovement  ();
#line 476 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 477 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
else 
#line 478 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 480 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
SetDesiredTranslation  (FLOAT3D (0 , 0 , 0));
#line 481 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 482 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return ulFlags ;
#line 483 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
ULONG CUnit::SetDesiredMovement(void) 
#line 490 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 491 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ULONG  ulFlags  = 0;
#line 542 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ulFlags  = SetDesiredRotate  ();
#line 545 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(m_fMoveSpeed  > 0.0f)
#line 546 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 547 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vDeltaPlane  = m_vDesiredPosition  - GetPlacement  () . pl_PositionVector ;
#line 548 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vDeltaPlane  (2) = 0.0f;
#line 550 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT fLength  = vDeltaPlane  . Length  ();
#line 565 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vDeltaPlane  . Normalize  ();
#line 567 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(fLength  < m_fMoveSpeed  * m_fMoveFrequency )
#line 568 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 570 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
m_fMoveSpeed  = fLength  / m_fMoveFrequency ;
#line 571 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 573 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vSpeed  = vDeltaPlane  * m_fMoveSpeed ;
#line 574 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT fTestLength  = vSpeed  . Length  ();
#line 575 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
SetDesiredTranslation  (vSpeed );
#line 576 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ulFlags  |= MF_MOVEZ ;
#line 577 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return ulFlags ;
#line 578 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 579 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
else 
#line 580 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 582 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
SetDesiredTranslation  (FLOAT3D (0 , 0 , 0));
#line 583 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 584 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return ulFlags ;
#line 585 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
ULONG CUnit::SetDesiredRotate(void) 
#line 588 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 589 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ULONG  ulFlags  = 0;
#line 592 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vDelta  = m_vDesiredPosition  - GetPlacement  () . pl_PositionVector ;
#line 593 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vDelta  (2) = 0.0f;
#line 596 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(m_aRotateSpeed  > 0.0f)
#line 597 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 599 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
FLOAT3D vDir  = vDelta ;
#line 600 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
vDir  . SafeNormalize  ();
#line 601 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ANGLE aWantedHeadingRelative  = GetRelativeHeading  (vDir );
#line 604 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
aWantedHeadingRelative  = NormalizeAngle  (aWantedHeadingRelative );
#line 606 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ANGLE aHeadingRotation ;
#line 608 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(aWantedHeadingRelative  < - m_aRotateSpeed  * m_fMoveFrequency )
#line 609 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 611 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
aHeadingRotation  = - m_aRotateSpeed ;
#line 613 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 614 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
else if(aWantedHeadingRelative  > m_aRotateSpeed  * m_fMoveFrequency )
#line 615 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 617 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
aHeadingRotation  = + m_aRotateSpeed ;
#line 619 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 620 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
else 
#line 621 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 623 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
aHeadingRotation  = aWantedHeadingRelative  / m_fMoveFrequency ;
#line 624 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 626 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
SetDesiredRotation  (ANGLE3D (aHeadingRotation  , 0 , 0));
#line 628 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
if(Abs  (aHeadingRotation ) > 1.0f)
#line 629 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 630 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
ulFlags  |= MF_ROTATEH ;
#line 631 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 634 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 635 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
else 
#line 636 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 638 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
SetDesiredRotation  (ANGLE3D (0 , 0 , 0));
#line 639 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
#line 640 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return ulFlags ;
#line 641 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 649 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
void CUnit::StopMoving() 
#line 650 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 651 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
StopRotating  ();
#line 652 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
StopTranslating  ();
#line 653 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 656 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
void CUnit::StopRotating() 
#line 657 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 658 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
SetDesiredRotation  (ANGLE3D (0 , 0 , 0));
#line 659 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}

#line 662 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
void CUnit::StopTranslating() 
#line 663 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 664 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
SetDesiredTranslation  (FLOAT3D (0.0f , 0.0f , 0.0f));
#line 665 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
void CUnit::StandingAnim(void) {}
void CUnit::WalkingAnim(void) {}
void CUnit::RunningAnim(void) {}
void CUnit::RotatingAnim(void) {}
void CUnit::AttackAnim(void) {}
void CUnit::HungryAnim(void) {}
void CUnit::ActEventAnim(void) {}

#line 685 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
BOOL CUnit::IsValidForEnemy(CEntity * penPlayer) 
#line 686 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
{
#line 687 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
return 
#line 688 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
penPlayer  != NULL  && 
#line 691 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
penPlayer  -> GetFlags  () & ENF_ALIVE ;
#line 692 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
}
BOOL CUnit::
#line 695 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CUnit_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CUnit::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 697 "F:/SD-Source/mandra/Reco_Csrc/EntitiesMP/Unit.es"
InitAsVoid  (); ASSERT(FALSE); return TRUE;};